In [58]:
from spisea import synthetic, evolution
from spisea import atmospheres, reddening
import numpy as np
import pandas as pd

In [2]:
import pdb

In [75]:
# Define isochrone input parameters
logAge = np.log10(5*10**6.) # Age in log(years)
dist = 4000 # distance in parsec
AKs = 0.0 # extinction in Ks-band mags
metallicity = 0 # Metallicity in [M/H]
evo_model = evolution.MISTv1()
atm_func = atmospheres.get_merged_atmosphere
red_law = reddening.RedLawHosek18b()

In [122]:
# Specify filters for synthetic photometry. Here we
# use  the HST WFC3-IR F127M, F139M, and F153M filters
filt_list = ['wfc3,ir,f127m', 'wfc3,ir,f139m',
'wfc3,ir,f153m', 'wfc3,uvis2,f814w', '2mass,H']

# Specify the directory we want the output isochrone
# table saved in
iso_dir = '/Users/mhuston/Documents/synthpop/synthpop/data/isochrones/spisea/'

# Make IsochronePhot object
my_iso = synthetic.Isochrone(logAge, AKs, dist,
                          metallicity=0,
                          evo_model=evo_model,
                          atm_func=atm_func,
                          red_law=red_law),
                          #filters=filt_list,
                          #iso_dir=iso_dir, recomp=True)

Changing to logg=4.00 for T= 31490 logg=3.99
Changing to logg=4.00 for T= 31687 logg=3.98
Changing to logg=4.00 for T= 31875 logg=3.97
Changing to logg=4.00 for T= 32138 logg=3.96
Changing to logg=4.00 for T= 32375 logg=3.94
Changing to logg=4.00 for T= 32571 logg=3.93
Changing to logg=4.00 for T= 32752 logg=3.91
Changing to logg=4.00 for T= 32915 logg=3.90
Changing to logg=4.00 for T= 33091 logg=3.88
Changing to logg=4.00 for T= 33258 logg=3.86
Changing to logg=4.00 for T= 33403 logg=3.84
Changing to logg=4.00 for T= 33524 logg=3.82
Changing to logg=4.00 for T= 33562 logg=3.81
Changing to logg=4.00 for T= 33597 logg=3.81
Changing to logg=4.00 for T= 33627 logg=3.80
Changing to logg=4.00 for T= 33654 logg=3.79
Changing to logg=4.00 for T= 33676 logg=3.78
Changing to logg=4.00 for T= 33690 logg=3.77
Changing to logg=4.00 for T= 33683 logg=3.75
Changing to logg=4.00 for T= 33642 logg=3.72
Changing to logg=4.00 for T= 33576 logg=3.70
Changing to logg=4.00 for T= 33508 logg=3.68
Changing to logg=4.00 for T= 33427 logg=3.67
Changing to logg=4.00 for T= 33330 logg=3.65
Changing to logg=4.00 for T= 33218 logg=3.63
Changing to logg=4.00 for T= 33105 logg=3.61
Changing to logg=4.00 for T= 32986 logg=3.60
Changing to logg=4.00 for T= 32863 logg=3.58
Changing to logg=4.00 for T= 32732 logg=3.57
Changing to logg=4.00 for T= 32596 logg=3.55
Changing to logg=4.00 for T= 32460 logg=3.54
Changing to logg=4.00 for T= 32301 logg=3.52
Changing to logg=4.00 for T= 32069 logg=3.50
Changing to logg=4.00 for T= 31830 logg=3.48
Changing to logg=4.00 for T= 31584 logg=3.46
Changing to logg=4.00 for T= 31331 logg=3.44
Changing to logg=4.00 for T= 31072 logg=3.41
Changing to logg=3.50 for T= 30797 logg=3.39
Changing to logg=3.50 for T= 30353 logg=3.35
Changing to logg=3.50 for T= 29909 logg=3.31
Changing to logg=3.50 for T= 29462 logg=3.27
Changing to logg=3.50 for T= 29103 logg=3.24
Changing to logg=3.50 for T= 28843 logg=3.21
Changing to logg=3.50 for T= 28582 logg=3.19
Changing to logg=3.50 for T= 28322 logg=3.17
Changing to logg=3.50 for T= 28061 logg=3.15
Changing to logg=3.50 for T= 27801 logg=3.13
Changing to logg=3.50 for T= 27542 logg=3.11
Changing to logg=3.50 for T= 27283 logg=3.09
Changing to logg=3.50 for T= 27028 logg=3.06
Changing to logg=3.50 for T= 26776 logg=3.04
Changing to logg=3.50 for T= 26530 logg=3.02
Changing to logg=3.50 for T= 26304 logg=3.00
Changing to logg=3.50 for T= 26182 logg=2.98
Changing to logg=3.50 for T= 26226 logg=2.98
Changing to logg=3.50 for T= 26411 logg=2.99
Changing to logg=3.50 for T= 26636 logg=3.00
Changing to logg=3.50 for T= 26871 logg=3.01
Changing to logg=3.50 for T= 27110 logg=3.03
Changing to logg=3.50 for T= 27350 logg=3.04
Changing to logg=3.50 for T= 27588 logg=3.05
Changing to logg=3.50 for T= 27823 logg=3.07
Changing to logg=3.50 for T= 28053 logg=3.08
Changing to logg=3.50 for T= 28278 logg=3.09
Changing to logg=3.50 for T= 28499 logg=3.10
Changing to logg=3.50 for T= 28715 logg=3.11
Changing to logg=3.50 for T= 28930 logg=3.12
Changing to logg=3.50 for T= 29140 logg=3.13
Changing to logg=3.50 for T= 29350 logg=3.14
Changing to logg=3.50 for T= 29555 logg=3.15
Changing to logg=3.50 for T= 29759 logg=3.16
Changing to logg=3.50 for T= 29951 logg=3.17
Changing to logg=3.50 for T= 30115 logg=3.18
Changing to logg=3.50 for T= 30204 logg=3.19
Changing to logg=3.50 for T= 30141 logg=3.18
Changing to logg=3.50 for T= 29947 logg=3.17
Changing to logg=3.50 for T= 29682 logg=3.16
Changing to logg=3.50 for T= 29399 logg=3.15
Changing to logg=3.50 for T= 29110 logg=3.13
Changing to logg=3.50 for T= 28819 logg=3.11
Changing to logg=3.50 for T= 28530 logg=3.10
Changing to logg=3.50 for T= 28239 logg=3.08
Changing to logg=3.50 for T= 27948 logg=3.06
Changing to logg=3.50 for T= 27666 logg=3.04
Changing to logg=3.50 for T= 27385 logg=3.02
Changing to logg=3.50 for T= 27106 logg=3.00
Changing to logg=3.50 for T= 26831 logg=2.98
Changing to logg=3.50 for T= 26560 logg=2.96
Changing to logg=3.50 for T= 26291 logg=2.94
Changing to logg=3.50 for T= 26026 logg=2.92
Changing to logg=3.00 for T= 25762 logg=2.90
Changing to logg=3.00 for T= 25501 logg=2.88
Changing to logg=3.00 for T= 25243 logg=2.86
Changing to logg=3.00 for T= 24986 logg=2.84
Changing to logg=3.00 for T= 24733 logg=2.82
Changing to logg=3.00 for T= 24482 logg=2.80
Changing to logg=3.00 for T= 24229 logg=2.78
Changing to logg=3.00 for T= 23980 logg=2.77
Changing to logg=3.00 for T= 23734 logg=2.75
Changing to logg=3.00 for T= 23491 logg=2.73
Changing to logg=3.00 for T= 23250 logg=2.71
Changing to logg=3.00 for T= 23011 logg=2.69
Changing to logg=3.00 for T= 22775 logg=2.67
Changing to logg=3.00 for T= 22542 logg=2.65
Changing to logg=3.00 for T= 22311 logg=2.63
Changing to logg=3.00 for T= 22082 logg=2.61
Changing to logg=3.00 for T= 21856 logg=2.59
Changing to logg=3.00 for T= 21632 logg=2.57
Changing to logg=3.00 for T= 21412 logg=2.55
Changing to logg=3.00 for T= 21196 logg=2.53
Changing to logg=3.00 for T= 20985 logg=2.52
Changing to logg=3.00 for T= 20777 logg=2.50
Changing to logg=3.00 for T= 20569 logg=2.48
Changing to logg=3.00 for T= 20413 logg=2.47
Changing to logg=3.00 for T= 20258 logg=2.46
Changing to logg=3.00 for T= 20103 logg=2.44
Changing to logg=3.00 for T= 19948 logg=2.43
Changing to logg=3.00 for T= 19794 logg=2.42
Changing to logg=3.00 for T= 19642 logg=2.40
Changing to logg=3.00 for T= 19490 logg=2.39
Changing to logg=3.00 for T= 19339 logg=2.38
Changing to logg=3.00 for T= 19189 logg=2.36
Changing to logg=3.00 for T= 19040 logg=2.35
Changing to logg=2.50 for T= 18892 logg=2.34
Changing to logg=2.50 for T= 18745 logg=2.32
Changing to logg=2.50 for T= 18599 logg=2.31
Changing to logg=2.50 for T= 18455 logg=2.29
Changing to logg=2.50 for T= 18311 logg=2.28
Changing to logg=2.50 for T= 18168 logg=2.27
Changing to logg=2.50 for T= 18027 logg=2.25
Changing to logg=2.50 for T= 17886 logg=2.24
Changing to logg=2.50 for T= 17747 logg=2.23
Changing to logg=2.50 for T= 17608 logg=2.21
Changing to logg=2.50 for T= 17471 logg=2.20
Changing to logg=2.50 for T= 17335 logg=2.19
Changing to logg=2.50 for T= 17199 logg=2.17
Changing to logg=2.50 for T= 17065 logg=2.16
Changing to logg=2.50 for T= 16931 logg=2.14
Changing to logg=2.50 for T= 16799 logg=2.13
Changing to logg=2.50 for T= 16668 logg=2.12
Changing to logg=2.50 for T= 16537 logg=2.10
Changing to logg=2.50 for T= 16408 logg=2.09
Changing to logg=2.50 for T= 16280 logg=2.08
Changing to logg=2.50 for T= 16152 logg=2.06
Changing to logg=2.50 for T= 16026 logg=2.05
Changing to logg=2.50 for T= 15900 logg=2.03
Changing to logg=2.50 for T= 15776 logg=2.02
Changing to logg=2.50 for T= 15652 logg=2.01
Changing to logg=2.50 for T= 15530 logg=1.99
Changing to logg=2.50 for T= 15408 logg=1.98
Changing to logg=2.50 for T= 15287 logg=1.96
Changing to logg=2.50 for T= 15168 logg=1.95
Changing to logg=2.50 for T= 15049 logg=1.94
Changing to logg=2.50 for T= 14931 logg=1.92
Changing to logg=2.50 for T= 14814 logg=1.91
Changing to logg=2.50 for T= 14698 logg=1.90
Changing to logg=2.50 for T= 14582 logg=1.88
Changing to logg=2.50 for T= 14468 logg=1.87
Changing to logg=2.50 for T= 14354 logg=1.85
Changing to logg=2.50 for T= 14242 logg=1.84
Changing to logg=2.50 for T= 14130 logg=1.83
Changing to logg=2.50 for T= 14019 logg=1.81
Changing to logg=2.50 for T= 13909 logg=1.80
Changing to logg=2.50 for T= 13800 logg=1.79
Changing to logg=2.50 for T= 13691 logg=1.77
Changing to logg=2.50 for T= 13584 logg=1.76
Changing to logg=2.50 for T= 13477 logg=1.74
Changing to logg=2.50 for T= 13371 logg=1.73
Changing to logg=2.50 for T= 13266 logg=1.72
Changing to logg=2.50 for T= 13162 logg=1.70
Changing to logg=2.50 for T= 13058 logg=1.69
Changing to logg=2.50 for T= 12955 logg=1.67
Changing to logg=2.50 for T= 12854 logg=1.66
Changing to logg=2.50 for T= 12753 logg=1.65
Changing to logg=2.50 for T= 12652 logg=1.63
Changing to logg=2.50 for T= 12553 logg=1.62
Changing to logg=2.50 for T= 12454 logg=1.61
Changing to logg=2.50 for T= 12356 logg=1.59
Changing to logg=2.50 for T= 12259 logg=1.58
Changing to logg=2.50 for T= 12162 logg=1.56
Changing to logg=2.50 for T= 12067 logg=1.55
Changing to logg=2.50 for T= 11972 logg=1.54
Changing to logg=2.50 for T= 11878 logg=1.52
Changing to logg=2.50 for T= 11784 logg=1.51
Changing to logg=2.00 for T= 11691 logg=1.49
Changing to logg=2.00 for T= 11600 logg=1.48
Changing to logg=2.00 for T= 11508 logg=1.47
Changing to logg=2.00 for T= 11418 logg=1.45
Changing to logg=2.00 for T= 11328 logg=1.44
Changing to logg=2.00 for T= 11239 logg=1.43
Changing to logg=2.00 for T= 11150 logg=1.41
Changing to logg=2.00 for T= 11063 logg=1.40
Changing to logg=2.00 for T= 10976 logg=1.38
Changing to logg=2.00 for T= 10889 logg=1.37
Changing to logg=2.00 for T= 10803 logg=1.36
Changing to logg=2.00 for T= 10718 logg=1.34
Changing to logg=2.00 for T= 10634 logg=1.33
Changing to logg=2.00 for T= 10550 logg=1.31
Changing to logg=2.00 for T= 10467 logg=1.30
Changing to logg=2.00 for T= 10385 logg=1.29
Changing to logg=2.00 for T= 10303 logg=1.27
Changing to logg=2.00 for T= 10222 logg=1.26
Changing to logg=2.00 for T= 10142 logg=1.24
Changing to logg=2.00 for T= 10062 logg=1.23
Changing to logg=2.00 for T=  9983 logg=1.22
Changing to logg=2.00 for T=  9904 logg=1.20
Changing to logg=2.00 for T=  9826 logg=1.19
Changing to logg=2.00 for T=  9749 logg=1.17
Changing to logg=2.00 for T=  9672 logg=1.16
Changing to logg=2.00 for T=  9596 logg=1.15
Changing to logg=2.00 for T=  9520 logg=1.13
Changing to logg=2.00 for T=  9445 logg=1.12
Changing to logg=2.00 for T=  9371 logg=1.10
Changing to logg=2.00 for T=  9297 logg=1.09
Changing to logg=2.00 for T=  9224 logg=1.08
Changing to logg=2.00 for T=  9151 logg=1.06
Changing to logg=2.00 for T=  9079 logg=1.05
Changing to logg=2.00 for T=  9008 logg=1.04
Changing to logg=1.50 for T=  8937 logg=1.02
Changing to logg=1.50 for T=  8866 logg=1.01
Changing to logg=1.50 for T=  8797 logg=0.99
Changing to logg=1.50 for T=  8727 logg=0.98
Changing to logg=1.50 for T=  8659 logg=0.97
Changing to logg=1.50 for T=  8590 logg=0.95
Changing to logg=1.50 for T=  8523 logg=0.94
Changing to logg=1.50 for T=  8456 logg=0.92
Changing to logg=1.50 for T=  8389 logg=0.91
Changing to logg=1.50 for T=  8323 logg=0.90
Changing to logg=1.50 for T=  8257 logg=0.88
Changing to logg=1.00 for T=  8192 logg=0.87
Changing to logg=1.00 for T=  8128 logg=0.85
Changing to logg=1.00 for T=  8064 logg=0.84
Changing to logg=1.00 for T=  8000 logg=0.83
Changing to logg=1.00 for T=  7937 logg=0.81
Changing to logg=1.00 for T=  7874 logg=0.80
Changing to logg=1.00 for T=  7812 logg=0.78
Changing to logg=1.00 for T=  7751 logg=0.77
Changing to logg=1.00 for T=  7689 logg=0.76
Changing to logg=1.00 for T=  7629 logg=0.74
Changing to logg=1.00 for T=  7568 logg=0.73
Changing to logg=1.00 for T=  7509 logg=0.71
Changing to logg=0.50 for T=  6666 logg=0.50
Changing to logg=0.50 for T=  6613 logg=0.49
Changing to logg=0.50 for T=  6561 logg=0.47
Changing to logg=0.50 for T=  6509 logg=0.46
Changing to logg=0.50 for T=  6457 logg=0.44
Changing to logg=0.50 for T=  6406 logg=0.43
Changing to logg=0.50 for T=  6355 logg=0.41
Changing to logg=0.50 for T=  6307 logg=0.39
Changing to logg=0.50 for T=  6257 logg=0.38
Changing to logg=0.50 for T=  6231 logg=0.37
Changing to logg=0.50 for T=  6206 logg=0.36
Changing to logg=0.50 for T=  6181 logg=0.36
Changing to logg=0.50 for T=  6156 logg=0.35
Changing to logg=0.50 for T=  6131 logg=0.34
Changing to logg=0.50 for T=  6107 logg=0.33
Changing to logg=0.50 for T=  6082 logg=0.33
Changing to logg=0.50 for T=  6057 logg=0.32
Changing to logg=0.50 for T=  6033 logg=0.31
Changing to logg=0.50 for T=  6009 logg=0.31
Changing to logg=1.00 for T=  7532 logg=0.60
Changing to logg=1.00 for T=  7575 logg=0.61
Changing to logg=1.00 for T=  7658 logg=0.63
Changing to logg=1.00 for T=  7753 logg=0.65
Changing to logg=1.00 for T=  7814 logg=0.66
Changing to logg=1.00 for T=  7899 logg=0.68
Changing to logg=1.00 for T=  7983 logg=0.70
Changing to logg=1.00 for T=  8067 logg=0.71
Changing to logg=1.00 for T=  8159 logg=0.73
Changing to logg=1.50 for T=  8262 logg=0.75
Changing to logg=1.50 for T=  8321 logg=0.76
Changing to logg=1.50 for T=  8400 logg=0.78
Changing to logg=1.50 for T=  8499 logg=0.80
Changing to logg=1.50 for T=  8593 logg=0.81
Changing to logg=1.50 for T=  8689 logg=0.83
Changing to logg=1.50 for T=  8772 logg=0.85
Changing to logg=1.50 for T=  8913 logg=0.87
Changing to logg=1.50 for T=  8969 logg=0.88
Changing to logg=2.00 for T=  9058 logg=0.90
Changing to logg=2.00 for T=  9190 logg=0.92
Changing to logg=2.00 for T=  9265 logg=0.93
Changing to logg=2.00 for T=  9398 logg=0.96
Changing to logg=2.00 for T=  9500 logg=0.97
Changing to logg=2.00 for T=  9626 logg=1.00
Changing to logg=2.00 for T=  9764 logg=1.02
Changing to logg=2.00 for T=  9876 logg=1.04
Changing to logg=2.00 for T=  9980 logg=1.06
Changing to logg=2.00 for T= 10096 logg=1.08
Changing to logg=2.00 for T= 10242 logg=1.10
Changing to logg=2.00 for T= 10368 logg=1.12
Changing to logg=2.00 for T= 10495 logg=1.14
Changing to logg=2.00 for T= 10626 logg=1.16
Changing to logg=2.00 for T= 10771 logg=1.19
Changing to logg=2.00 for T= 10898 logg=1.21
Changing to logg=2.00 for T= 11024 logg=1.23
Changing to logg=2.00 for T= 10997 logg=1.22
Changing to logg=2.00 for T= 11089 logg=1.24
Changing to logg=2.00 for T= 11189 logg=1.25
Changing to logg=2.00 for T= 11376 logg=1.28
Changing to logg=2.00 for T= 11480 logg=1.29
Changing to logg=2.00 for T= 11641 logg=1.31
Changing to logg=2.00 for T= 11697 logg=1.32
Changing to logg=2.50 for T= 11855 logg=1.34
Changing to logg=2.50 for T= 12035 logg=1.37
Changing to logg=2.50 for T= 12212 logg=1.39
Changing to logg=2.50 for T= 12366 logg=1.41
Changing to logg=2.50 for T= 12553 logg=1.43
Changing to logg=2.50 for T= 12767 logg=1.46
Changing to logg=2.50 for T= 12988 logg=1.49
Changing to logg=2.50 for T= 13198 logg=1.51
Changing to logg=2.50 for T= 13425 logg=1.54
Changing to logg=2.50 for T= 13659 logg=1.56
Changing to logg=2.50 for T= 13896 logg=1.59
Changing to logg=2.50 for T= 14133 logg=1.62
Changing to logg=2.50 for T= 14378 logg=1.64
Changing to logg=2.50 for T= 14642 logg=1.67
Changing to logg=2.50 for T= 14925 logg=1.70
Changing to logg=2.50 for T= 15110 logg=1.71
Changing to logg=2.50 for T= 14985 logg=1.69
Changing to logg=2.50 for T= 14862 logg=1.67
Changing to logg=2.50 for T= 14741 logg=1.64
Changing to logg=2.50 for T= 14645 logg=1.62
Changing to logg=2.50 for T= 14527 logg=1.60
Changing to logg=2.50 for T= 14821 logg=1.63
Changing to logg=2.50 for T= 15356 logg=1.68
Changing to logg=2.50 for T= 15587 logg=1.70
Changing to logg=2.50 for T= 15629 logg=1.70
Changing to logg=2.50 for T= 15623 logg=1.70
Changing to logg=2.50 for T= 15620 logg=1.70
Changing to logg=2.50 for T= 15616 logg=1.70
Changing to logg=2.50 for T= 15612 logg=1.70
Changing to logg=2.50 for T= 15607 logg=1.70
Changing to logg=2.50 for T= 15601 logg=1.70
Changing to logg=2.50 for T= 15594 logg=1.70
Changing to logg=2.50 for T= 15566 logg=1.69
Changing to logg=2.50 for T= 15527 logg=1.69
Changing to logg=2.50 for T= 15489 logg=1.68
Changing to logg=2.50 for T= 15464 logg=1.68
Changing to logg=2.50 for T= 15447 logg=1.68
Changing to logg=2.50 for T= 15439 logg=1.68
Changing to logg=2.50 for T= 15430 logg=1.68
Changing to logg=2.50 for T= 15420 logg=1.68
Changing to logg=2.50 for T= 15407 logg=1.67
Changing to logg=2.50 for T= 15393 logg=1.67
Changing to logg=2.50 for T= 15379 logg=1.67
Changing to logg=2.50 for T= 15364 logg=1.67
Changing to logg=2.50 for T= 15349 logg=1.66
Changing to logg=2.50 for T= 15334 logg=1.66
Changing to logg=2.50 for T= 15320 logg=1.66
Changing to logg=2.50 for T= 15307 logg=1.65
Changing to logg=2.50 for T= 15295 logg=1.65
Changing to logg=2.50 for T= 15287 logg=1.65
Changing to logg=2.50 for T= 15282 logg=1.64
Changing to logg=2.50 for T= 15279 logg=1.64
Changing to logg=2.50 for T= 15277 logg=1.64
Changing to logg=2.50 for T= 15311 logg=1.64
Changing to logg=2.50 for T= 15333 logg=1.64
Changing to logg=2.50 for T= 15320 logg=1.63
Changing to logg=2.50 for T= 15307 logg=1.62
Changing to logg=2.50 for T= 15303 logg=1.62
Changing to logg=2.50 for T= 15307 logg=1.62
Changing to logg=2.50 for T= 15317 logg=1.61
Changing to logg=2.50 for T= 15333 logg=1.61
Changing to logg=2.50 for T= 15349 logg=1.62
Changing to logg=2.50 for T= 15366 logg=1.62
Changing to logg=2.50 for T= 15385 logg=1.62
Changing to logg=2.50 for T= 15401 logg=1.62
Changing to logg=2.50 for T= 15404 logg=1.62
Changing to logg=2.50 for T= 15416 logg=1.62
Changing to logg=2.50 for T= 15429 logg=1.62
Changing to logg=2.50 for T= 15446 logg=1.62
Changing to logg=2.50 for T= 15458 logg=1.62
Changing to logg=2.50 for T= 15464 logg=1.62
Changing to logg=2.50 for T= 15475 logg=1.63
Changing to logg=2.50 for T= 15482 logg=1.63
Changing to logg=2.50 for T= 15487 logg=1.63
Changing to logg=2.50 for T= 15495 logg=1.63
Changing to logg=2.50 for T= 15509 logg=1.63
Changing to logg=2.50 for T= 15507 logg=1.63
Changing to logg=2.50 for T= 15518 logg=1.63
Changing to logg=2.50 for T= 15520 logg=1.63
Changing to logg=2.50 for T= 15532 logg=1.63
Changing to logg=2.50 for T= 15538 logg=1.63
Changing to logg=2.50 for T= 15541 logg=1.63
Changing to logg=2.50 for T= 15550 logg=1.63
Changing to logg=2.50 for T= 15554 logg=1.63
Changing to logg=2.50 for T= 15544 logg=1.63
Changing to logg=2.50 for T= 15539 logg=1.63
Changing to logg=2.50 for T= 15536 logg=1.63
Changing to logg=2.50 for T= 15531 logg=1.63
Changing to logg=2.50 for T= 15524 logg=1.63
Changing to logg=2.50 for T= 15517 logg=1.63
Changing to logg=2.50 for T= 15512 logg=1.62
Changing to logg=2.50 for T= 15508 logg=1.62
Changing to logg=2.50 for T= 15503 logg=1.62
Changing to logg=2.50 for T= 15498 logg=1.62
Changing to logg=2.50 for T= 15494 logg=1.62
Changing to logg=2.50 for T= 15497 logg=1.62
Changing to logg=2.50 for T= 15503 logg=1.62
Changing to logg=2.50 for T= 15509 logg=1.63
Changing to logg=2.50 for T= 15515 logg=1.63
Changing to logg=2.50 for T= 15521 logg=1.63
Changing to logg=2.50 for T= 15527 logg=1.63
Changing to logg=2.50 for T= 15534 logg=1.63
Changing to logg=2.50 for T= 15541 logg=1.63
Changing to logg=2.50 for T= 15547 logg=1.63
Changing to logg=2.50 for T= 15554 logg=1.63
Changing to logg=2.50 for T= 15561 logg=1.63
Changing to logg=2.50 for T= 15568 logg=1.63
Changing to logg=2.50 for T= 15575 logg=1.63
Changing to logg=2.50 for T= 15582 logg=1.63
Changing to logg=2.50 for T= 15589 logg=1.64
Changing to logg=2.50 for T= 15596 logg=1.64
Changing to logg=2.50 for T= 15603 logg=1.64
Changing to logg=2.50 for T= 15609 logg=1.64
Changing to logg=2.50 for T= 15616 logg=1.64
Changing to logg=2.50 for T= 15622 logg=1.64
Changing to logg=2.50 for T= 15628 logg=1.64
Changing to logg=2.50 for T= 15635 logg=1.64
Changing to logg=2.50 for T= 15641 logg=1.64
Changing to logg=2.50 for T= 15647 logg=1.64
Changing to logg=2.50 for T= 15653 logg=1.64
Changing to logg=2.50 for T= 15658 logg=1.64
Changing to logg=2.50 for T= 15664 logg=1.64
Changing to logg=2.50 for T= 15670 logg=1.64
Changing to logg=2.50 for T= 15675 logg=1.65
Changing to logg=2.50 for T= 15680 logg=1.65
Changing to logg=2.50 for T= 15686 logg=1.65
Changing to logg=2.50 for T= 15691 logg=1.65
Isochrone generation took 14.677438 s.

In [117]:
my_iso.version

AttributeError: 'IsochronePhot' object has no attribute 'version'

In [112]:
my_iso.filters

['wfc3,ir,f127m',
 'wfc3,ir,f139m',
 'wfc3,ir,f153m',
 'wfc3,uvis2,f814w',
 '2mass,H']

In [1]:
import synthpop as sp

/Users/mhuston/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
  warnings.warn(message, UserWarning)

In [2]:
spmod = sp.SynthPop(name_for_output='test', default_config='huston2025_defaults.synthpop_conf')
spmod.init_populations()

 5493 - Execution Date: 15-05-2025 16:17:06


################################ Settings #################################
 5494 - # reading default parameters from
 5494 - default_config_file =  /Users/mhuston/Documents/synthpop/synthpop/config_files/huston2025_defaults.synthpop_conf


# copy the following to a config file to redo this model generation -------
 5495 - {
    "l_set": null,
    "l_set_type": null,
    "b_set": null,
    "b_set_type": null,
    "random_seed": 751981571,
    "name_for_output": "test",
    "model_name": "Huston2025",
    "solid_angle": null,
    "solid_angle_unit": "deg^2",
    "sun": {
        "x": -8.178,
        "y": 0.0,
        "z": 0.017,
        "u": 12.9,
        "v": 245.6,
        "w": 7.78,
        "l_apex_deg": 56.24,
        "b_apex_deg": 22.54
    },
    "lsr": {
        "u_lsr": 1.8,
        "v_lsr": 233.4,
        "w_lsr": 0.53
    },
    "warp": {
        "r_warp": 7.72,
        "amp_warp": 0.06,
        "amp_warp_pos": null,
        "amp_warp_neg": null,
        "alpha_warp": 1.33,
        "phi_warp_deg": 17.5
    },
    "extinction_map_kwargs": {
        "name": "Surot",
        "project_3d": true,
        "dist_2d": 8.15
    },
    "extinction_law_kwargs": [
        {
            "name": "SODC",
            "R_V": 2.5
        }
    ],
    "max_distance": 25,
    "distance_step_size": 0.1,
    "window_type": {
        "window_type": "cone"
    },
    "mass_lims": {
        "min_mass": 0.08,
        "max_mass": 100
    },
    "N_mc_totmass": 10000,
    "lost_mass_option": 1,
    "N_av_mass": 50000,
    "kinematics_at_the_end": false,
    "scale_factor": 1,
    "skip_lowmass_stars": false,
    "chunk_size": 250000,
    "evolution_class": {
        "name": "MIST",
        "interpolator": "CharonInterpolator"
    },
    "maglim": [
        "W146",
        23.975533,
        "remove"
    ],
    "chosen_bands": [
        "R062",
        "Z087",
        "Y106",
        "J129",
        "W146",
        "H158",
        "F184",
        "Bessell_U",
        "Bessell_B",
        "Bessell_V",
        "Bessell_R",
        "Bessell_I",
        "VISTA_J",
        "VISTA_H",
        "VISTA_Ks"
    ],
    "eff_wavelengths": {
        "R062": 0.615778,
        "Z087": 0.86339,
        "Y106": 1.045809,
        "J129": 1.2747,
        "W146": 1.30138,
        "H158": 1.558247,
        "F184": 1.830067,
        "Bessell_U": 0.365988,
        "Bessell_B": 0.438074,
        "Bessell_V": 0.544543,
        "Bessell_R": 0.641147,
        "Bessell_I": 0.798209,
        "VISTA_J": 1.255579,
        "VISTA_H": 1.649872,
        "VISTA_Ks": 2.15779
    },
    "obsmag": true,
    "opt_iso_props": [
        "log_L",
        "log_Teff",
        "log_g",
        "[Fe/H]",
        "log_R",
        "phase"
    ],
    "col_names": [
        "logL",
        "logTeff",
        "logg",
        "Fe/H_evolved",
        "log_radius",
        "phase"
    ],
    "post_processing_kwargs": [
        {
            "name": "ProcessDarkCompactObjects",
            "remove": false
        },
        {
            "name": "ConvertMistMags",
            "conversions": {
                "AB": [
                    "R062",
                    "Z087",
                    "Y106",
                    "J129",
                    "W146",
                    "H158",
                    "F184"
                ]
            }
        }
    ],
    "output_location": "outputfiles/default",
    "output_filename_pattern": "{name_for_output}_l{l_deg:.3f}_b{b_deg:.3f}",
    "output_file_type": "csv",
    "overwrite": true
}
 5496 - Location or solid_angle_sr are not  defined in the settings! Can not run main() or process_all()


########################## initialize population ##########################
 5498 - read Population files from Huston2025


# Population 0;  bulge ----------------------------------------------------
 5501 - # Initialize Population 0 (bulge) from
 5501 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/bulge.popjson'


# Population 1;  halo -----------------------------------------------------
 26142 - # Initialize Population 1 (halo) from
 26142 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/halo.popjson'


# Population 2;  nsd ------------------------------------------------------
 26797 - # Initialize Population 2 (nsd) from
 26797 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/nsd.popjson'


# Population 3;  thick_disk -----------------------------------------------
 27888 - # Initialize Population 3 (thick_disk) from
 27894 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thick_disk.popjson'


# Population 4;  thin_disk_1 ----------------------------------------------
 28575 - # Initialize Population 4 (thin_disk_1) from
 28576 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_1.popjson'


# Population 5;  thin_disk_2 ----------------------------------------------
 29257 - # Initialize Population 5 (thin_disk_2) from
 29257 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_2.popjson'


# Population 6;  thin_disk_3 ----------------------------------------------
 29977 - # Initialize Population 6 (thin_disk_3) from
 29978 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_3.popjson'


# Population 7;  thin_disk_4 ----------------------------------------------
 30825 - # Initialize Population 7 (thin_disk_4) from
 30826 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_4.popjson'


# Population 8;  thin_disk_5 ----------------------------------------------
 31584 - # Initialize Population 8 (thin_disk_5) from
 31584 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_5.popjson'


# Population 9;  thin_disk_6 ----------------------------------------------
 32312 - # Initialize Population 9 (thin_disk_6) from
 32313 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_6.popjson'


# Population 10;  thin_disk_7 ---------------------------------------------
 33033 - # Initialize Population 10 (thin_disk_7) from
 33034 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/thin_disk_7.popjson'
 33713 - # all population are initialized

In [74]:
mist_isos = spmod.populations[0].evolution.isochrones
mist_isos

,log_R,H158,log_Teff,phase,W146,R062,F184,star_mass,Z087,log10_isochrone_age_yr,...,log_g,Y106,Bessell_V,Bessell_B,Bessell_I,Bessell_R,Bessell_U,VISTA_J,VISTA_H,VISTA_Ks
0,0.043787,3.985190,3.617011,-1.0,4.320230,6.120077,3.810673,0.100000,5.111601,5.0,...,3.350571,4.760768,6.645812,7.805105,5.284892,5.949971,8.279037,4.411981,3.908688,3.727125
1,0.050254,3.945770,3.618039,-1.0,4.280550,6.073921,3.771948,0.102885,5.069485,5.0,...,3.347798,4.720180,6.596900,7.749505,5.241930,5.904354,8.213431,4.372238,3.869333,3.689235
2,0.059829,3.887368,3.619556,-1.0,4.221797,6.005664,3.714574,0.107147,5.007198,5.0,...,3.343658,4.660136,6.524569,7.667323,5.178397,5.836895,8.116573,4.313419,3.811020,3.633105
3,0.069304,3.829506,3.621062,-1.0,4.163620,5.938120,3.657734,0.111379,4.945580,5.0,...,3.339612,4.600729,6.452992,7.585987,5.115542,5.770147,8.020796,4.255189,3.753243,3.577507
4,0.078680,3.772214,3.622555,-1.0,4.106044,5.871332,3.601455,0.115581,4.884656,5.0,...,3.335660,4.541980,6.382214,7.505559,5.053394,5.704152,7.926188,4.197572,3.696033,3.522462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108718,-1.806255,10.635622,4.402490,6.0,10.581017,10.033175,10.717831,0.532726,10.320126,10.3,...,7.777159,10.515989,9.953986,9.804964,10.218862,10.075529,8.799999,10.582170,10.652210,10.754732
108719,-1.809295,10.697798,4.387132,6.0,10.646828,10.112968,10.779277,0.532730,10.392982,10.3,...,7.783242,10.584676,10.035246,9.898314,10.293137,10.154106,8.913713,10.647722,10.713973,10.814684
108720,-1.812237,10.756705,4.371789,6.0,10.709302,10.189516,10.837441,0.532735,10.462471,10.3,...,7.789130,10.650011,10.113359,9.988331,10.364065,10.229397,9.024037,10.709810,10.772529,10.871462
108721,-1.815091,10.812930,4.356480,6.0,10.769053,10.263439,10.892908,0.532741,10.529238,10.3,...,7.794844,10.712618,10.188924,10.075726,10.432288,10.302034,9.131856,10.769149,10.828431,10.925624
108722,-1.817854,10.866999,4.341226,6.0,10.826623,10.335249,10.946223,0.532749,10.593838,10.3,...,7.800376,10.773043,10.262406,10.161068,10.498350,10.372540,9.237886,10.826392,10.882181,10.977690

In [48]:
mist_isos.keys()

Index(['log_R', 'H158', 'log_Teff', 'phase', 'W146', 'R062', 'F184',
       'star_mass', 'Z087', 'log10_isochrone_age_yr', '[Fe/H]_init', 'log_L',
       'J129', '[Fe/H]', 'initial_mass', 'log_g', 'Y106', 'Bessell_V',
       'Bessell_B', 'Bessell_I', 'Bessell_R', 'Bessell_U', 'VISTA_J',
       'VISTA_H', 'VISTA_Ks'],
      dtype='object')

In [57]:
mist_isos['[Fe/H]_init']

0        -4.0
1        -4.0
2        -4.0
3        -4.0
4        -4.0
         ...
108718    0.5
108719    0.5
108720    0.5
108721    0.5
108722    0.5
Name: [Fe/H]_init, Length: 1494453, dtype: float64

In [65]:
mp = my_iso.to_pandas()

In [66]:
mp['hey']=0

In [67]:
mp

,L,Teff,R,mass,logg,isWR,mass_current,phase,m_hst_f127m,m_hst_f139m,m_hst_f153m,hey
0,8.256006e+24,2985.198018,3.819688e+08,0.100000,3.958886,False,0.100000,-1.0,19.785653,19.850611,19.577463,0
1,8.526563e+24,2993.484850,3.860309e+08,0.103064,3.960489,False,0.103064,-1.0,19.753485,19.815144,19.542276,0
2,8.891345e+24,3004.293175,3.913707e+08,0.107025,3.962506,False,0.107025,-1.0,19.712841,19.769432,19.496898,0
3,9.271538e+24,3015.199385,3.967647e+08,0.110986,3.964567,False,0.110986,-1.0,19.673942,19.724227,19.451990,0
4,9.667792e+24,3026.175172,4.022210e+08,0.114948,3.966658,False,0.114948,-1.0,19.635134,19.679220,19.407285,0
...,...,...,...,...,...,...,...,...,...,...,...,...
717,3.117322e+32,15669.518361,8.518611e+10,45.592367,1.644968,True,24.148543,9.0,4.624312,4.653397,4.655826,0
718,3.116954e+32,15674.955709,8.512198e+10,45.592370,1.645622,True,24.148540,9.0,4.625490,4.654585,4.657024,0
719,3.116585e+32,15680.311462,8.505882e+10,45.592371,1.646267,True,24.148537,9.0,4.626652,4.655756,4.658205,0
720,3.116214e+32,15685.591800,8.499650e+10,45.592373,1.646903,True,24.148534,9.0,4.627801,4.656913,4.659371,0
721,3.115839e+32,15690.801923,8.493495e+10,45.592374,1.647532,True,24.148532,9.0,4.628936,4.658058,4.660525,0

In [47]:
spisea_filts = {
    '2mass':['J','H','Ks'],
    'ctio_osiris':['H','K'],
    'decam':['u','g','r','i','z','Y'],
    'gaia':{'dr2_rev':['G','Gbp','Grp']},
    'hawki':['J','H','Ks'],
    # Add any more hubble??
    'wfc3':{'uvis1':['f200lp', 'f218w', 'f225w', 'f275w', 'f280n', 'f300x',
                     'f336w', 'f343n', 'f350lp', 'f373n', 'f390m', 'f390w',
                     'f395n', 'f410m', 'f438w', 'f467m', 'f469n', 'f475w',
                     'f475x', 'f487n', 'f502n', 'f547m', 'f555w', 'f600lp',
                     'f606w', 'f621m', 'f625w', 'f631n', 'f645n', 'f656n',
                     'f657n', 'f658n', 'f665n', 'f673n', 'f680n', 'f689m',
                     'f763m', 'f775w', 'f814w', 'f845m', 'f850lp', 'f953n',
                     'fq232n', 'fq243n', 'fq378n', 'fq387n', 'fq422m', 'fq436n',
                     'fq437n', 'fq492n', 'fq508n', 'fq575n', 'fq619n', 'fq634n',
                     'fq672n', 'fq674n', 'fq727n', 'fq750n', 'fq889n', 'fq906n', 
                     'fq924n', 'fq937n'],
            'uvis2':['f200lp', 'f218w', 'f225w', 'f275w', 'f280n', 'f300x',
                     'f336w', 'f343n', 'f350lp', 'f373n', 'f390m', 'f390w',
                     'f395n', 'f410m', 'f438w', 'f467m', 'f469n', 'f475w',
                     'f475x', 'f487n', 'f502n', 'f547m', 'f555w', 'f600lp',
                     'f606w', 'f621m', 'f625w', 'f631n', 'f645n', 'f656n',
                     'f657n', 'f658n', 'f665n', 'f673n', 'f680n', 'f689m',
                     'f763m', 'f775w', 'f814w', 'f845m', 'f850lp', 'f953n',
                     'fq232n', 'fq243n', 'fq378n', 'fq387n', 'fq422m', 'fq436n',
                     'fq437n', 'fq492n', 'fq508n', 'fq575n', 'fq619n', 'fq634n',
                     'fq672n', 'fq674n', 'fq727n', 'fq750n', 'fq889n', 'fq906n', 
                     'fq924n', 'fq937n'],
            'ir':['f098m', 'f105w', 'f110w', 'f125w', 'f126n', 'f127m',
                  'f128n', 'f130n', 'f132n', 'f139m', 'f140w', 'f153m',
                  'f160w', 'f164n', 'f167n']},
    'acs':{'hrc':['f220w', 'f250w', 'f330w', 'f344n', 'f435w', 'f475w', 'f502n',
                  'f550m', 'f555w', 'f606w', 'f625w', 'f658n', 'f660n', 'f775w',
                  'f814w', 'f850lp', 'f892n', 'pol_uv', 'pol_v'],
           'sbc':['f115lp', 'f125lp', 'f140lp', 'f150lp', 'f165lp', 'f122m'],
           'wfc1':['f435w', 'f475w', 'f502n', 'f550m', 'f555w', 'f606w', 'f625w', 
                   'f658n', 'f660n', 'f775w', 'f814w', 'f850lp', 'f892n', 
                   'pol_uv', 'pol_v'],
           'wfc2':['f435w', 'f475w', 'f502n', 'f550m', 'f555w', 'f606w', 'f625w', 
                   'f658n', 'f660n', 'f775w', 'f814w', 'f850lp', 'f892n', 
                   'pol_uv', 'pol_v']},
    'ubv':['U','B','V','R','I'],
    'jg': ['J','H','K'],
    'jwst':['F070W', 'F090W', 'F115W', 'F140M', 'F150W', 'F150W2', 'F162M', 
            'F164N', 'F182M', 'F187N', 'F200W', 'F210M', 'F212N', 'F250M', 
            'F277W', 'F300M', 'F322W2', 'F323N', 'F335M', 'F356W', 'F360M', 
            'F405N', 'F410M', 'F430M', 'F444W', 'F460M', 'F466N', 'F470N', 
            'F480M'],
    'nirc1':['H', 'K'],
    'nirc2':['J','H','K','Kp','Ks','Kcont','Lp','Ms','Brgamma','FeII'],
    'naco':['J','H','Ks'],
    'ps1':['g','r','i','z','y'],
    'roman':{'wfi':['F062','F087','F106','F129','F158','W146','F184','F213']},
    'ukirt':['J','H','K'],
    'rubin':['u','g','r','i','z','y'],
    'vista':['Z','Y','J','H','K'],
    'ztf':['g','r','i']
}

In [48]:
for x in spisea_filts:
    print(x)

2mass
ctio_osiris
decam
gaia
hawki
wfc3
acs
ubv
jg
jwst
nirc1
nirc2
naco
ps1
roman
ukirt
rubin
vista
ztf

In [49]:
import synthpop as sp

/Users/mhuston/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
  warnings.warn(message, UserWarning)

In [ ]:
simod = sp.SynthPop(name_for_output='spisea_test', default_config='huston2025_defaults.synthpop_conf',
                    evolution_class={"name":"SpiseaIso", "interpolator":"CharonInterpolator"}, extinction_map_kwargs={'map_name':'NoExtinction'},
            opt_iso_props=["log_L", "log_Teff", "log_g", "log_R", "phase"],
            col_names=["logL", "logTeff", "logg" ,"log_radius","phase"],
                   chosen_bands=['2mass-J','2mass-H'], maglim=['2mass-J',99,'keep'],
                   eff_wavelengths={'json_file':'AAA_effective_wavelengths_spisea.json'},
                   post_processing_kwargs=[{"name": "ProcessDarkCompactObjects", "remove": False}])
simod.init_populations()

################################ Settings #################################
 2436267 - # reading default parameters from
 2436268 - default_config_file =  /Users/mhuston/Documents/synthpop/synthpop/config_files/huston2025_defaults.synthpop_conf


# copy the following to a config file to redo this model generation -------
 2436269 - {
    "l_set": null,
    "l_set_type": null,
    "b_set": null,
    "b_set_type": null,
    "random_seed": 1793831653,
    "name_for_output": "spisea_test",
    "model_name": "Huston2025",
    "solid_angle": null,
    "solid_angle_unit": "deg^2",
    "sun": {
        "x": -8.178,
        "y": 0.0,
        "z": 0.017,
        "u": 12.9,
        "v": 245.6,
        "w": 7.78,
        "l_apex_deg": 56.24,
        "b_apex_deg": 22.54
    },
    "lsr": {
        "u_lsr": 1.8,
        "v_lsr": 233.4,
        "w_lsr": 0.53
    },
    "warp": {
        "r_warp": 7.72,
        "amp_warp": 0.06,
        "amp_warp_pos": null,
        "amp_warp_neg": null,
        "alpha_warp": 1.33,
        "phi_warp_deg": 17.5
    },
    "extinction_map_kwargs": {
        "map_name": "NoExtinction"
    },
    "extinction_law_kwargs": [
        {
            "name": "SODC",
            "R_V": 2.5
        }
    ],
    "max_distance": 25,
    "distance_step_size": 0.1,
    "window_type": {
        "window_type": "cone"
    },
    "mass_lims": {
        "min_mass": 0.08,
        "max_mass": 100
    },
    "N_mc_totmass": 10000,
    "lost_mass_option": 1,
    "N_av_mass": 50000,
    "kinematics_at_the_end": false,
    "scale_factor": 1,
    "skip_lowmass_stars": false,
    "chunk_size": 250000,
    "evolution_class": {
        "name": "SpiseaIso",
        "interpolator": "CharonInterpolator"
    },
    "maglim": [
        "2mass-J",
        99,
        "keep"
    ],
    "chosen_bands": [
        "2mass-J",
        "2mass-H"
    ],
    "eff_wavelengths": {
        "json_file": "AAA_effective_wavelengths_spisea.json"
    },
    "obsmag": true,
    "opt_iso_props": [
        "log_L",
        "log_Teff",
        "log_g",
        "log_R",
        "phase"
    ],
    "col_names": [
        "logL",
        "logTeff",
        "logg",
        "log_radius",
        "phase"
    ],
    "post_processing_kwargs": [
        {
            "name": "ProcessDarkCompactObjects",
            "remove": false
        }
    ],
    "output_location": "outputfiles/default",
    "output_filename_pattern": "{name_for_output}_l{l_deg:.3f}_b{b_deg:.3f}",
    "output_file_type": "csv",
    "overwrite": true
}
 2436269 - Location or solid_angle_sr are not  defined in the settings! Can not run main() or process_all()


########################## initialize population ##########################
 2436270 - read Population files from Huston2025


# Population 0;  bulge ----------------------------------------------------
 2436271 - # Initialize Population 0 (bulge) from
 2436272 - pop_file = '/Users/mhuston/Documents/synthpop/synthpop/models/Huston2025/bulge.popjson'
Requested metallicity 1.3999999999999997e-06 is out of bounds.

[-4.00616031 -3.49907583 -3.00616031 -2.49907583 -2.00616031 -1.75434834
 -1.49907583 -1.24919836 -1.00616031 -0.75434834 -0.49907583 -0.24919836
 -0.00616031  0.24565166  0.50092417]
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4159 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4173 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4187 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4201 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4216 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4230 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4244 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4258 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4272 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4286 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4299 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4316 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4335 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4354 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4375 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4396 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4416 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4437 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4460 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4485 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4512 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4539 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4566 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4590 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4614 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4637 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4660 logg=3.24
Changing to met=-4.00 for met=-4.01 T=  4706 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4736 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4792 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4830 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4854 logg=3.21
Changing to met=-4.00 for met=-4.01 T=  4879 logg=3.21
Changing to met=-4.00 for met=-4.01 T=  4899 logg=3.21
Changing to met=-4.00 for met=-4.01 T=  4944 logg=3.20
Changing to met=-4.00 for met=-4.01 T=  4994 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5044 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5084 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5123 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5157 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5189 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5220 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5246 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5266 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5284 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5297 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5311 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5323 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5336 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5348 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5361 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5375 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5388 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5403 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5418 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5433 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5449 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5465 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5477 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5494 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5517 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5527 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5547 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5562 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5576 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5595 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5599 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5605 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5610 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5618 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5629 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5643 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5656 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  5670 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  5682 logg=3.13
Changing to met=-2.50 for met=-4.01 T=  5697 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  5703 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  5711 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  5738 logg=3.08
Changing to met=-2.50 for met=-4.01 T=  5753 logg=3.06
Changing to met=-2.50 for met=-4.01 T=  5779 logg=3.02
Changing to met=-2.50 for met=-4.01 T=  5807 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  5845 logg=2.90
Changing to met=-2.50 for met=-4.01 T=  5890 logg=2.82
Changing to met=-2.50 for met=-4.01 T=  5964 logg=2.76
Changing to met=-2.50 for met=-4.01 T=  6072 logg=2.72
Changing to met=-2.50 for met=-4.01 T=  6203 logg=2.71
Changing to met=-2.50 for met=-4.01 T=  6358 logg=2.71
Changing to met=-2.50 for met=-4.01 T=  6526 logg=2.73
Changing to met=-2.50 for met=-4.01 T=  6699 logg=2.76
Changing to met=-2.50 for met=-4.01 T=  6877 logg=2.78
Changing to met=-2.50 for met=-4.01 T=  7061 logg=2.81
Changing to met=-2.50 for met=-4.01 T=  7254 logg=2.84
Changing to met=-2.50 for met=-4.01 T=  7451 logg=2.86
Changing to met=-2.50 for met=-4.01 T=  7654 logg=2.89
Changing to met=-2.50 for met=-4.01 T=  7851 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  8052 logg=2.95
Changing to met=-2.50 for met=-4.01 T=  8258 logg=2.98
Changing to met=-2.50 for met=-4.01 T=  8469 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  8684 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  8902 logg=3.06
Changing to met=-2.50 for met=-4.01 T=  9126 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  9356 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  9594 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  9838 logg=3.17
Changing to met=-2.50 for met=-4.01 T= 10088 logg=3.20
Changing to met=-2.50 for met=-4.01 T= 10351 logg=3.23
Changing to met=-2.50 for met=-4.01 T= 10622 logg=3.26
Changing to met=-2.50 for met=-4.01 T= 10899 logg=3.28
Changing to met=-2.50 for met=-4.01 T= 11185 logg=3.31
Changing to met=-2.50 for met=-4.01 T= 11477 logg=3.34
Changing to met=-2.50 for met=-4.01 T= 11779 logg=3.37
Changing to met=-2.50 for met=-4.01 T= 12086 logg=3.40
Changing to met=-2.50 for met=-4.01 T= 12401 logg=3.43
Changing to met=-2.50 for met=-4.01 T= 12724 logg=3.46
Changing to met=-2.50 for met=-4.01 T= 13043 logg=3.49
Changing to met=-2.50 for met=-4.01 T= 13362 logg=3.52
Changing to met=-2.50 for met=-4.01 T= 13688 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 14899 logg=3.64
Changing to met=-2.50 for met=-4.01 T= 15078 logg=3.66
Changing to met=-2.50 for met=-4.01 T= 16950 logg=3.80
Changing to met=-2.50 for met=-4.01 T= 16764 logg=3.78
Changing to met=-2.50 for met=-4.01 T= 14951 logg=3.59
Changing to met=-2.50 for met=-4.01 T= 18030 logg=3.86
Changing to met=-2.50 for met=-4.01 T= 18744 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 19205 logg=3.94
Changing to met=-2.50 for met=-4.01 T= 19066 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 19531 logg=3.94
Changing to met=-2.50 for met=-4.01 T= 20826 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 21373 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 21935 logg=4.08
Changing to met=-2.50 for met=-4.01 T= 22512 logg=4.11
Changing to met=-2.50 for met=-4.01 T= 23104 logg=4.14
Changing to met=-2.50 for met=-4.01 T= 23707 logg=4.17
Changing to met=-2.50 for met=-4.01 T= 24312 logg=4.20
Changing to met=-2.50 for met=-4.01 T= 24926 logg=4.23
Changing to met=-2.50 for met=-4.01 T= 25553 logg=4.26
Changing to met=-2.50 for met=-4.01 T= 26194 logg=4.29
Changing to met=-2.50 for met=-4.01 T= 26847 logg=4.32
Changing to met=-2.50 for met=-4.01 T= 27513 logg=4.34
Changing to met=-2.50 for met=-4.01 T= 28193 logg=4.37
Changing to met=-2.50 for met=-4.01 T= 28887 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 29597 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 30316 logg=4.45
Changing to met=-2.50 for met=-4.01 T= 31019 logg=4.47
Changing to met=-2.50 for met=-4.01 T= 31739 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 32477 logg=4.52
Changing to met=-2.50 for met=-4.01 T= 33231 logg=4.54
Changing to met=-2.50 for met=-4.01 T= 33998 logg=4.57
Changing to met=-2.50 for met=-4.01 T= 34785 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 35723 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 36705 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 37721 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 38779 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 39786 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 40638 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 41207 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 41116 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 40413 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 39836 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 40399 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 40739 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 41061 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 41424 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 41846 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42388 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42748 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43098 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43434 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43790 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44164 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44650 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45114 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45495 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45897 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46311 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46734 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47151 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47617 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48100 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48574 logg=4.79
Changing to logg=5.00 for T= 49065 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49065 logg=4.79
Changing to logg=5.00 for T= 49580 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49580 logg=4.79
Changing to T= 50000 for T= 50088 logg=4.78
Changing to logg=5.00 for T= 50088 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50088 logg=4.78
Changing to T= 50000 for T= 50596 logg=4.78
Changing to logg=5.00 for T= 50596 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50596 logg=4.78
Changing to T= 50000 for T= 51129 logg=4.78
Changing to logg=5.00 for T= 51129 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51129 logg=4.78
Changing to T= 50000 for T= 51657 logg=4.78
Changing to logg=5.00 for T= 51657 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51657 logg=4.78
Changing to T= 50000 for T= 52184 logg=4.78
Changing to logg=5.00 for T= 52184 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52184 logg=4.78
Changing to T= 50000 for T= 52730 logg=4.78
Changing to logg=5.00 for T= 52730 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52730 logg=4.78
Changing to T= 50000 for T= 53277 logg=4.77
Changing to logg=5.00 for T= 53277 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53277 logg=4.77
Changing to T= 50000 for T= 53826 logg=4.77
Changing to logg=5.00 for T= 53826 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53826 logg=4.77
Changing to T= 50000 for T= 54387 logg=4.77
Changing to logg=5.00 for T= 54387 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54387 logg=4.77
Changing to T= 50000 for T= 54952 logg=4.77
Changing to logg=5.00 for T= 54952 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54952 logg=4.77
Changing to T= 50000 for T= 55521 logg=4.77
Changing to logg=5.00 for T= 55521 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55521 logg=4.77
Changing to T= 50000 for T= 56036 logg=4.77
Changing to logg=5.00 for T= 56036 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 56036 logg=4.77
Changing to T= 50000 for T= 56470 logg=4.77
Changing to logg=5.00 for T= 56470 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 56470 logg=4.77
Changing to T= 50000 for T= 56908 logg=4.76
Changing to logg=5.00 for T= 56908 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56908 logg=4.76
Changing to T= 50000 for T= 57838 logg=4.76
Changing to logg=5.00 for T= 57838 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57838 logg=4.76
Changing to T= 50000 for T= 58270 logg=4.76
Changing to logg=5.00 for T= 58270 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58270 logg=4.76
Changing to T= 50000 for T= 59171 logg=4.76
Changing to logg=5.00 for T= 59171 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 59171 logg=4.76
Changing to T= 50000 for T= 59668 logg=4.76
Changing to logg=5.00 for T= 59668 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 59668 logg=4.76
Changing to T= 50000 for T= 60097 logg=4.75
Changing to logg=5.00 for T= 60097 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60097 logg=4.75
Changing to T= 50000 for T= 60462 logg=4.75
Changing to logg=5.00 for T= 60462 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60462 logg=4.75
Changing to T= 50000 for T= 60970 logg=4.75
Changing to logg=5.00 for T= 60970 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60970 logg=4.75
Changing to T= 50000 for T= 61322 logg=4.75
Changing to logg=5.00 for T= 61322 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61322 logg=4.75
Changing to T= 50000 for T= 61675 logg=4.75
Changing to logg=5.00 for T= 61675 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61675 logg=4.75
Changing to T= 50000 for T= 62047 logg=4.75
Changing to logg=5.00 for T= 62047 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62047 logg=4.75
Changing to T= 50000 for T= 62423 logg=4.75
Changing to logg=5.00 for T= 62423 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62423 logg=4.75
Changing to T= 50000 for T= 62798 logg=4.75
Changing to logg=5.00 for T= 62798 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62798 logg=4.75
Changing to T= 50000 for T= 63170 logg=4.75
Changing to logg=5.00 for T= 63170 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 63170 logg=4.75
Changing to T= 50000 for T= 63570 logg=4.75
Changing to logg=5.00 for T= 63570 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 63570 logg=4.75
Changing to T= 50000 for T= 63977 logg=4.74
Changing to logg=5.00 for T= 63977 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63977 logg=4.74
Changing to T= 50000 for T= 64381 logg=4.74
Changing to logg=5.00 for T= 64381 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64381 logg=4.74
Changing to T= 50000 for T= 65022 logg=4.74
Changing to logg=5.00 for T= 65022 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65022 logg=4.74
Changing to T= 50000 for T= 65722 logg=4.74
Changing to logg=5.00 for T= 65722 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65722 logg=4.74
Changing to T= 50000 for T= 66431 logg=4.74
Changing to logg=5.00 for T= 66431 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 66431 logg=4.74
Changing to T= 50000 for T= 68852 logg=4.69
Changing to logg=5.00 for T= 68852 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 68852 logg=4.69
Changing to T= 50000 for T= 69294 logg=4.69
Changing to logg=5.00 for T= 69294 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 69294 logg=4.69
Changing to T= 50000 for T= 69746 logg=4.69
Changing to logg=5.00 for T= 69746 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 69746 logg=4.69
Changing to T= 50000 for T= 70231 logg=4.69
Changing to logg=5.00 for T= 70231 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 70231 logg=4.69
Changing to T= 50000 for T= 71847 logg=4.68
Changing to logg=5.00 for T= 71847 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 71847 logg=4.68
Changing to T= 50000 for T= 72092 logg=4.68
Changing to logg=5.00 for T= 72092 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72092 logg=4.68
Changing to T= 50000 for T= 72516 logg=4.68
Changing to logg=5.00 for T= 72516 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72516 logg=4.68
Changing to T= 50000 for T= 73729 logg=4.69
Changing to logg=5.00 for T= 73729 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 73729 logg=4.69
Changing to T= 50000 for T= 74156 logg=4.69
Changing to logg=5.00 for T= 74156 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74156 logg=4.69
Changing to T= 50000 for T= 74619 logg=4.69
Changing to logg=5.00 for T= 74619 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74619 logg=4.69
Changing to T= 50000 for T= 75219 logg=4.69
Changing to logg=5.00 for T= 75219 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 75219 logg=4.69
Changing to T= 50000 for T= 75829 logg=4.68
Changing to logg=5.00 for T= 75829 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75829 logg=4.68
Changing to T= 50000 for T= 76417 logg=4.68
Changing to logg=5.00 for T= 76417 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 76417 logg=4.68
Changing to T= 50000 for T= 77016 logg=4.67
Changing to logg=5.00 for T= 77016 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 77016 logg=4.67
Changing to T= 50000 for T= 77600 logg=4.67
Changing to logg=5.00 for T= 77600 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 77600 logg=4.67
Isochrone generation took 5.230426 s.
Making photometry for isochrone: log(t) = 5.01  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:26.354804   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.106 Msun  T =  4159 K  m_2mass_J = 4.53
M =   4.459 Msun  T =  8902 K  m_2mass_J = -2.19

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  39.792 Msun  T = 59668 K  m_2mass_J = -2.69
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.106 Msun  T =  4159 K  m_2mass_H = 4.01
M =   4.459 Msun  T =  8902 K  m_2mass_H = -2.21
M =  39.792 Msun  T = 59668 K  m_2mass_H = -2.57
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4137 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4147 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4161 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4176 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4190 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4204 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4219 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4233 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4247 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4261 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4274 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4288 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4301 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4318 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4338 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4359 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4380 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4400 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4421 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4442 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4466 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4493 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4520 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4548 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4575 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4599 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4622 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4645 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4668 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4721 logg=3.24
Changing to met=-4.00 for met=-4.01 T=  4752 logg=3.24
Changing to met=-4.00 for met=-4.01 T=  4811 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4850 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4864 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4886 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4908 logg=3.22
Changing to met=-4.00 for met=-4.01 T=  4959 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  5016 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  5065 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5101 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5137 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5171 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5201 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5231 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5258 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5275 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5292 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5304 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5316 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5329 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5341 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5354 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5367 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5381 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5395 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5410 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5425 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5441 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5457 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5473 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5488 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5502 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5520 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5540 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5562 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5577 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5586 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5603 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5615 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5618 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5621 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5624 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5636 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  5656 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5671 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5685 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  5697 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  5716 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5721 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  5726 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  5764 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  5766 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  5801 logg=3.04
Changing to met=-2.50 for met=-4.01 T=  5842 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  5890 logg=2.89
Changing to met=-2.50 for met=-4.01 T=  5950 logg=2.82
Changing to met=-2.50 for met=-4.01 T=  6023 logg=2.76
Changing to met=-2.50 for met=-4.01 T=  6164 logg=2.74
Changing to met=-2.50 for met=-4.01 T=  6328 logg=2.74
Changing to met=-2.50 for met=-4.01 T=  6495 logg=2.76
Changing to met=-2.50 for met=-4.01 T=  6667 logg=2.78
Changing to met=-2.50 for met=-4.01 T=  6844 logg=2.81
Changing to met=-2.50 for met=-4.01 T=  7026 logg=2.84
Changing to met=-2.50 for met=-4.01 T=  7213 logg=2.86
Changing to met=-2.50 for met=-4.01 T=  7404 logg=2.89
Changing to met=-2.50 for met=-4.01 T=  7600 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  7807 logg=2.95
Changing to met=-2.50 for met=-4.01 T=  8019 logg=2.98
Changing to met=-2.50 for met=-4.01 T=  8237 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  8458 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  8670 logg=3.06
Changing to met=-2.50 for met=-4.01 T=  8888 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  9111 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  9340 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  9574 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  9815 logg=3.20
Changing to met=-2.50 for met=-4.01 T= 10061 logg=3.23
Changing to met=-2.50 for met=-4.01 T= 10316 logg=3.25
Changing to met=-2.50 for met=-4.01 T= 10578 logg=3.28
Changing to met=-2.50 for met=-4.01 T= 10847 logg=3.31
Changing to met=-2.50 for met=-4.01 T= 11124 logg=3.34
Changing to met=-2.50 for met=-4.01 T= 11417 logg=3.37
Changing to met=-2.50 for met=-4.01 T= 11716 logg=3.40
Changing to met=-2.50 for met=-4.01 T= 12023 logg=3.43
Changing to met=-2.50 for met=-4.01 T= 12338 logg=3.46
Changing to met=-2.50 for met=-4.01 T= 12660 logg=3.49
Changing to met=-2.50 for met=-4.01 T= 12989 logg=3.52
Changing to met=-2.50 for met=-4.01 T= 13327 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 13673 logg=3.57
Changing to met=-2.50 for met=-4.01 T= 14028 logg=3.60
Changing to met=-2.50 for met=-4.01 T= 16893 logg=3.86
Changing to met=-2.50 for met=-4.01 T= 14900 logg=3.66
Changing to met=-2.50 for met=-4.01 T= 16393 logg=3.78
Changing to met=-2.50 for met=-4.01 T= 16529 logg=3.79
Changing to met=-2.50 for met=-4.01 T= 18094 logg=3.90
Changing to met=-2.50 for met=-4.01 T= 18415 logg=3.93
Changing to met=-2.50 for met=-4.01 T= 16012 logg=3.70
Changing to met=-2.50 for met=-4.01 T= 16282 logg=3.73
Changing to met=-2.50 for met=-4.01 T= 20230 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 20762 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 21309 logg=4.08
Changing to met=-2.50 for met=-4.01 T= 21870 logg=4.11
Changing to met=-2.50 for met=-4.01 T= 22446 logg=4.14
Changing to met=-2.50 for met=-4.01 T= 23036 logg=4.17
Changing to met=-2.50 for met=-4.01 T= 23642 logg=4.20
Changing to met=-2.50 for met=-4.01 T= 24262 logg=4.23
Changing to met=-2.50 for met=-4.01 T= 24898 logg=4.26
Changing to met=-2.50 for met=-4.01 T= 25544 logg=4.29
Changing to met=-2.50 for met=-4.01 T= 26188 logg=4.32
Changing to met=-2.50 for met=-4.01 T= 26843 logg=4.35
Changing to met=-2.50 for met=-4.01 T= 27512 logg=4.37
Changing to met=-2.50 for met=-4.01 T= 28192 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 28888 logg=4.43
Changing to met=-2.50 for met=-4.01 T= 29599 logg=4.45
Changing to met=-2.50 for met=-4.01 T= 30325 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 31067 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 31825 logg=4.53
Changing to met=-2.50 for met=-4.01 T= 32594 logg=4.55
Changing to met=-2.50 for met=-4.01 T= 33344 logg=4.58
Changing to met=-2.50 for met=-4.01 T= 34114 logg=4.60
Changing to met=-2.50 for met=-4.01 T= 34906 logg=4.63
Changing to met=-2.50 for met=-4.01 T= 35720 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 36556 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 37465 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 38540 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 39524 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 40194 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 40189 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 39484 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 38832 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 39462 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 39803 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 40132 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40497 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40918 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41381 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41671 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41965 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42309 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42702 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43093 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43462 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43807 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44161 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44591 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45102 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45575 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45963 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46354 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46761 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47159 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47611 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48111 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48603 logg=4.79
Changing to logg=5.00 for T= 49094 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49094 logg=4.79
Changing to logg=5.00 for T= 49613 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49613 logg=4.79
Changing to T= 50000 for T= 50124 logg=4.78
Changing to logg=5.00 for T= 50124 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50124 logg=4.78
Changing to T= 50000 for T= 50632 logg=4.78
Changing to logg=5.00 for T= 50632 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50632 logg=4.78
Changing to T= 50000 for T= 51163 logg=4.78
Changing to logg=5.00 for T= 51163 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51163 logg=4.78
Changing to T= 50000 for T= 51694 logg=4.78
Changing to logg=5.00 for T= 51694 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51694 logg=4.78
Changing to T= 50000 for T= 52224 logg=4.78
Changing to logg=5.00 for T= 52224 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52224 logg=4.78
Changing to T= 50000 for T= 52769 logg=4.78
Changing to logg=5.00 for T= 52769 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52769 logg=4.78
Changing to T= 50000 for T= 53317 logg=4.77
Changing to logg=5.00 for T= 53317 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53317 logg=4.77
Changing to T= 50000 for T= 53866 logg=4.77
Changing to logg=5.00 for T= 53866 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53866 logg=4.77
Changing to T= 50000 for T= 54429 logg=4.77
Changing to logg=5.00 for T= 54429 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54429 logg=4.77
Changing to T= 50000 for T= 54995 logg=4.77
Changing to logg=5.00 for T= 54995 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54995 logg=4.77
Changing to T= 50000 for T= 55567 logg=4.77
Changing to logg=5.00 for T= 55567 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55567 logg=4.77
Changing to T= 50000 for T= 56145 logg=4.77
Changing to logg=5.00 for T= 56145 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 56145 logg=4.77
Changing to T= 50000 for T= 56588 logg=4.76
Changing to logg=5.00 for T= 56588 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56588 logg=4.76
Changing to T= 50000 for T= 56993 logg=4.76
Changing to logg=5.00 for T= 56993 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56993 logg=4.76
Changing to T= 50000 for T= 57647 logg=4.76
Changing to logg=5.00 for T= 57647 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57647 logg=4.76
Changing to T= 50000 for T= 58431 logg=4.76
Changing to logg=5.00 for T= 58431 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58431 logg=4.76
Changing to T= 50000 for T= 58868 logg=4.76
Changing to logg=5.00 for T= 58868 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58868 logg=4.76
Changing to T= 50000 for T= 59981 logg=4.75
Changing to logg=5.00 for T= 59981 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59981 logg=4.75
Changing to T= 50000 for T= 60324 logg=4.75
Changing to logg=5.00 for T= 60324 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60324 logg=4.75
Changing to T= 50000 for T= 60669 logg=4.75
Changing to logg=5.00 for T= 60669 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60669 logg=4.75
Changing to T= 50000 for T= 61026 logg=4.75
Changing to logg=5.00 for T= 61026 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61026 logg=4.75
Changing to T= 50000 for T= 61388 logg=4.75
Changing to logg=5.00 for T= 61388 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61388 logg=4.75
Changing to T= 50000 for T= 61752 logg=4.75
Changing to logg=5.00 for T= 61752 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61752 logg=4.75
Changing to T= 50000 for T= 62116 logg=4.75
Changing to logg=5.00 for T= 62116 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62116 logg=4.75
Changing to T= 50000 for T= 62500 logg=4.75
Changing to logg=5.00 for T= 62500 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62500 logg=4.75
Changing to T= 50000 for T= 62892 logg=4.75
Changing to logg=5.00 for T= 62892 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62892 logg=4.75
Changing to T= 50000 for T= 63284 logg=4.75
Changing to logg=5.00 for T= 63284 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 63284 logg=4.75
Changing to T= 50000 for T= 63670 logg=4.74
Changing to logg=5.00 for T= 63670 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63670 logg=4.74
Changing to T= 50000 for T= 64075 logg=4.74
Changing to logg=5.00 for T= 64075 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64075 logg=4.74
Changing to T= 50000 for T= 64504 logg=4.74
Changing to logg=5.00 for T= 64504 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64504 logg=4.74
Changing to T= 50000 for T= 65116 logg=4.74
Changing to logg=5.00 for T= 65116 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65116 logg=4.74
Changing to T= 50000 for T= 65882 logg=4.74
Changing to logg=5.00 for T= 65882 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65882 logg=4.74
Changing to T= 50000 for T= 66660 logg=4.74
Changing to logg=5.00 for T= 66660 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 66660 logg=4.74
Changing to T= 50000 for T= 67469 logg=4.73
Changing to logg=5.00 for T= 67469 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67469 logg=4.73
Changing to T= 50000 for T= 69970 logg=4.67
Changing to logg=5.00 for T= 69970 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 69970 logg=4.67
Changing to T= 50000 for T= 70325 logg=4.67
Changing to logg=5.00 for T= 70325 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70325 logg=4.67
Changing to T= 50000 for T= 70745 logg=4.67
Changing to logg=5.00 for T= 70745 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70745 logg=4.67
Changing to T= 50000 for T= 72179 logg=4.68
Changing to logg=5.00 for T= 72179 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72179 logg=4.68
Changing to T= 50000 for T= 72416 logg=4.68
Changing to logg=5.00 for T= 72416 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72416 logg=4.68
Changing to T= 50000 for T= 72646 logg=4.68
Changing to logg=5.00 for T= 72646 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72646 logg=4.68
Changing to T= 50000 for T= 73434 logg=4.68
Changing to logg=5.00 for T= 73434 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 73434 logg=4.68
Changing to T= 50000 for T= 74315 logg=4.69
Changing to logg=5.00 for T= 74315 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74315 logg=4.69
Changing to T= 50000 for T= 74826 logg=4.69
Changing to logg=5.00 for T= 74826 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74826 logg=4.69
Changing to T= 50000 for T= 75411 logg=4.69
Changing to logg=5.00 for T= 75411 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 75411 logg=4.69
Changing to T= 50000 for T= 75982 logg=4.68
Changing to logg=5.00 for T= 75982 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75982 logg=4.68
Isochrone generation took 5.166337 s.
Making photometry for isochrone: log(t) = 5.05  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:31.855906   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4137 K  m_2mass_J = 4.66
M =   4.262 Msun  T =  8670 K  m_2mass_J = -2.09
M =  34.812 Msun  T = 57647 K  m_2mass_J = -2.53
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4137 K  m_2mass_H = 4.14
M =   4.262 Msun  T =  8670 K  m_2mass_H = -2.13

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  34.812 Msun  T = 57647 K  m_2mass_H = -2.41
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4135 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4144 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4159 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4173 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4187 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4201 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4215 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4229 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4243 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4257 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4271 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4284 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4298 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4314 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4335 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4355 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4376 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4397 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4418 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4439 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4464 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4491 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4518 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4546 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4574 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4598 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4621 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4644 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4668 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4722 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4752 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4812 logg=3.24
Changing to met=-4.00 for met=-4.01 T=  4849 logg=3.24
Changing to met=-4.00 for met=-4.01 T=  4863 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4886 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4907 logg=3.23
Changing to met=-4.00 for met=-4.01 T=  4958 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5014 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  5064 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  5099 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  5134 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5168 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5198 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5228 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5257 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5274 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5290 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5304 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5316 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5328 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5341 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5354 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5368 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5382 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5396 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5411 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5426 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5442 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5458 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5475 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5493 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5504 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5522 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5548 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5558 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5580 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5594 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5608 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5628 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5630 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5633 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5636 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5647 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5660 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5679 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  5694 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  5708 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5721 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5738 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5744 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  5789 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  5790 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  5822 logg=3.07
Changing to met=-2.50 for met=-4.01 T=  5871 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  5932 logg=2.93
Changing to met=-2.50 for met=-4.01 T=  6007 logg=2.87
Changing to met=-2.50 for met=-4.01 T=  6098 logg=2.81
Changing to met=-2.50 for met=-4.01 T=  6218 logg=2.78
Changing to met=-2.50 for met=-4.01 T=  6394 logg=2.79
Changing to met=-2.50 for met=-4.01 T=  6577 logg=2.81
Changing to met=-2.50 for met=-4.01 T=  6760 logg=2.84
Changing to met=-2.50 for met=-4.01 T=  6939 logg=2.87
Changing to met=-2.50 for met=-4.01 T=  7123 logg=2.89
Changing to met=-2.50 for met=-4.01 T=  7311 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  7505 logg=2.95
Changing to met=-2.50 for met=-4.01 T=  7704 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  7908 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  8117 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  8334 logg=3.06
Changing to met=-2.50 for met=-4.01 T=  8560 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  8791 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  9028 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  9263 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  9495 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  9733 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  9977 logg=3.26
Changing to met=-2.50 for met=-4.01 T= 10228 logg=3.28
Changing to met=-2.50 for met=-4.01 T= 10484 logg=3.31
Changing to met=-2.50 for met=-4.01 T= 10747 logg=3.34
Changing to met=-2.50 for met=-4.01 T= 11017 logg=3.37
Changing to met=-2.50 for met=-4.01 T= 11297 logg=3.40
Changing to met=-2.50 for met=-4.01 T= 11583 logg=3.42
Changing to met=-2.50 for met=-4.01 T= 11877 logg=3.45
Changing to met=-2.50 for met=-4.01 T= 12183 logg=3.48
Changing to met=-2.50 for met=-4.01 T= 12502 logg=3.51
Changing to met=-2.50 for met=-4.01 T= 12828 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 13162 logg=3.57
Changing to met=-2.50 for met=-4.01 T= 13504 logg=3.60
Changing to met=-2.50 for met=-4.01 T= 13853 logg=3.63
Changing to met=-2.50 for met=-4.01 T= 14211 logg=3.66
Changing to met=-2.50 for met=-4.01 T= 14580 logg=3.69
Changing to met=-2.50 for met=-4.01 T= 14959 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 18490 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 15883 logg=3.77
Changing to met=-2.50 for met=-4.01 T= 16158 logg=3.80
Changing to met=-2.50 for met=-4.01 T= 17789 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 17932 logg=3.92
Changing to met=-2.50 for met=-4.01 T= 19675 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 17426 logg=3.85
Changing to met=-2.50 for met=-4.01 T= 17722 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 21649 logg=4.14
Changing to met=-2.50 for met=-4.01 T= 22220 logg=4.17
Changing to met=-2.50 for met=-4.01 T= 22805 logg=4.20
Changing to met=-2.50 for met=-4.01 T= 23405 logg=4.23
Changing to met=-2.50 for met=-4.01 T= 24020 logg=4.26
Changing to met=-2.50 for met=-4.01 T= 24650 logg=4.29
Changing to met=-2.50 for met=-4.01 T= 25296 logg=4.32
Changing to met=-2.50 for met=-4.01 T= 25958 logg=4.35
Changing to met=-2.50 for met=-4.01 T= 26636 logg=4.38
Changing to met=-2.50 for met=-4.01 T= 27322 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 28011 logg=4.43
Changing to met=-2.50 for met=-4.01 T= 28712 logg=4.46
Changing to met=-2.50 for met=-4.01 T= 29428 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 30153 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 30894 logg=4.53
Changing to met=-2.50 for met=-4.01 T= 31651 logg=4.56
Changing to met=-2.50 for met=-4.01 T= 32426 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 33220 logg=4.61
Changing to met=-2.50 for met=-4.01 T= 34035 logg=4.64
Changing to met=-2.50 for met=-4.01 T= 34858 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 35672 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 36502 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 37332 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 38109 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 38777 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 39109 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 38649 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 37962 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 38102 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 38558 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 38901 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39321 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39795 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40256 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40538 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40823 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41116 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41418 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41720 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42033 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42408 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42806 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43206 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43554 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43913 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44264 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44745 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45283 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45698 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46086 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46494 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46891 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47285 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47780 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48273 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48758 logg=4.79
Changing to logg=5.00 for T= 49271 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49271 logg=4.79
Changing to logg=5.00 for T= 49782 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49782 logg=4.79
Changing to T= 50000 for T= 50288 logg=4.78
Changing to logg=5.00 for T= 50288 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50288 logg=4.78
Changing to T= 50000 for T= 50814 logg=4.78
Changing to logg=5.00 for T= 50814 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50814 logg=4.78
Changing to T= 50000 for T= 51342 logg=4.78
Changing to logg=5.00 for T= 51342 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51342 logg=4.78
Changing to T= 50000 for T= 51867 logg=4.78
Changing to logg=5.00 for T= 51867 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51867 logg=4.78
Changing to T= 50000 for T= 52410 logg=4.78
Changing to logg=5.00 for T= 52410 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52410 logg=4.78
Changing to T= 50000 for T= 52954 logg=4.78
Changing to logg=5.00 for T= 52954 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52954 logg=4.78
Changing to T= 50000 for T= 53502 logg=4.77
Changing to logg=5.00 for T= 53502 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53502 logg=4.77
Changing to T= 50000 for T= 54060 logg=4.77
Changing to logg=5.00 for T= 54060 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54060 logg=4.77
Changing to T= 50000 for T= 54622 logg=4.77
Changing to logg=5.00 for T= 54622 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54622 logg=4.77
Changing to T= 50000 for T= 55192 logg=4.77
Changing to logg=5.00 for T= 55192 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55192 logg=4.77
Changing to T= 50000 for T= 55767 logg=4.77
Changing to logg=5.00 for T= 55767 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55767 logg=4.77
Changing to T= 50000 for T= 56328 logg=4.76
Changing to logg=5.00 for T= 56328 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56328 logg=4.76
Changing to T= 50000 for T= 56733 logg=4.76
Changing to logg=5.00 for T= 56733 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56733 logg=4.76
Changing to T= 50000 for T= 57145 logg=4.76
Changing to logg=5.00 for T= 57145 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57145 logg=4.76
Changing to T= 50000 for T= 58099 logg=4.76
Changing to logg=5.00 for T= 58099 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58099 logg=4.76
Changing to T= 50000 for T= 58598 logg=4.76
Changing to logg=5.00 for T= 58598 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58598 logg=4.76
Changing to T= 50000 for T= 59041 logg=4.76
Changing to logg=5.00 for T= 59041 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 59041 logg=4.76
Changing to T= 50000 for T= 60118 logg=4.75
Changing to logg=5.00 for T= 60118 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60118 logg=4.75
Changing to T= 50000 for T= 60469 logg=4.75
Changing to logg=5.00 for T= 60469 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60469 logg=4.75
Changing to T= 50000 for T= 60823 logg=4.75
Changing to logg=5.00 for T= 60823 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60823 logg=4.75
Changing to T= 50000 for T= 61189 logg=4.75
Changing to logg=5.00 for T= 61189 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61189 logg=4.75
Changing to T= 50000 for T= 61562 logg=4.75
Changing to logg=5.00 for T= 61562 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61562 logg=4.75
Changing to T= 50000 for T= 61939 logg=4.75
Changing to logg=5.00 for T= 61939 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61939 logg=4.75
Changing to T= 50000 for T= 62314 logg=4.75
Changing to logg=5.00 for T= 62314 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62314 logg=4.75
Changing to T= 50000 for T= 62702 logg=4.75
Changing to logg=5.00 for T= 62702 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62702 logg=4.75
Changing to T= 50000 for T= 63110 logg=4.75
Changing to logg=5.00 for T= 63110 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 63110 logg=4.75
Changing to T= 50000 for T= 63516 logg=4.74
Changing to logg=5.00 for T= 63516 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63516 logg=4.74
Changing to T= 50000 for T= 63919 logg=4.74
Changing to logg=5.00 for T= 63919 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63919 logg=4.74
Changing to T= 50000 for T= 64314 logg=4.74
Changing to logg=5.00 for T= 64314 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64314 logg=4.74
Changing to T= 50000 for T= 64828 logg=4.74
Changing to logg=5.00 for T= 64828 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64828 logg=4.74
Changing to T= 50000 for T= 65606 logg=4.74
Changing to logg=5.00 for T= 65606 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65606 logg=4.74
Changing to T= 50000 for T= 66404 logg=4.74
Changing to logg=5.00 for T= 66404 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 66404 logg=4.74
Changing to T= 50000 for T= 67217 logg=4.73
Changing to logg=5.00 for T= 67217 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67217 logg=4.73
Changing to T= 50000 for T= 68015 logg=4.73
Changing to logg=5.00 for T= 68015 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 68015 logg=4.73
Changing to T= 50000 for T= 70140 logg=4.67
Changing to logg=5.00 for T= 70140 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70140 logg=4.67
Changing to T= 50000 for T= 70488 logg=4.67
Changing to logg=5.00 for T= 70488 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70488 logg=4.67
Changing to T= 50000 for T= 70934 logg=4.67
Changing to logg=5.00 for T= 70934 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70934 logg=4.67
Changing to T= 50000 for T= 72276 logg=4.68
Changing to logg=5.00 for T= 72276 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72276 logg=4.68
Changing to T= 50000 for T= 72508 logg=4.68
Changing to logg=5.00 for T= 72508 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 72508 logg=4.68
Changing to T= 50000 for T= 73004 logg=4.68
Changing to logg=5.00 for T= 73004 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 73004 logg=4.68
Changing to T= 50000 for T= 74112 logg=4.69
Changing to logg=5.00 for T= 74112 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74112 logg=4.69
Changing to T= 50000 for T= 74577 logg=4.69
Changing to logg=5.00 for T= 74577 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74577 logg=4.69
Changing to T= 50000 for T= 75077 logg=4.69
Changing to logg=5.00 for T= 75077 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 75077 logg=4.69
Changing to T= 50000 for T= 75666 logg=4.68
Changing to logg=5.00 for T= 75666 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75666 logg=4.68
Changing to T= 50000 for T= 76259 logg=4.68
Changing to logg=5.00 for T= 76259 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 76259 logg=4.68
Isochrone generation took 5.251923 s.
Making photometry for isochrone: log(t) = 5.10  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:37.442464   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4135 K  m_2mass_J = 4.72
M =   4.123 Msun  T =  8791 K  m_2mass_J = -1.94
M =  32.914 Msun  T = 56733 K  m_2mass_J = -2.47
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4135 K  m_2mass_H = 4.21
M =   4.123 Msun  T =  8791 K  m_2mass_H = -1.97

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  32.914 Msun  T = 56733 K  m_2mass_H = -2.35
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4132 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4142 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4156 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4170 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4185 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4199 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4213 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4227 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4241 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4254 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4268 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4281 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4295 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4311 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4332 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4352 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4373 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4395 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4416 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4437 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4462 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4490 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4517 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4545 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4574 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4597 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4620 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4644 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4667 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4723 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4752 logg=3.26
Changing to met=-4.00 for met=-4.01 T=  4813 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4848 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4862 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4884 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4905 logg=3.25
Changing to met=-4.00 for met=-4.01 T=  4955 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5010 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5060 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5094 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  5128 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  5162 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5191 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5220 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5249 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5270 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5287 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5303 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5315 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5327 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5340 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5354 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5367 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5382 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5396 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5411 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5427 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5443 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5459 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5476 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5493 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5508 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5523 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5543 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5563 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5587 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5602 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5611 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5632 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5642 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5645 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5648 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5651 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5664 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5686 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  5703 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5719 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5736 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5756 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  5762 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  5769 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  5818 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  5852 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  5903 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  5976 logg=2.96
Changing to met=-2.50 for met=-4.01 T=  6066 logg=2.91
Changing to met=-2.50 for met=-4.01 T=  6175 logg=2.87
Changing to met=-2.50 for met=-4.01 T=  6306 logg=2.85
Changing to met=-2.50 for met=-4.01 T=  6458 logg=2.84
Changing to met=-2.50 for met=-4.01 T=  6640 logg=2.86
Changing to met=-2.50 for met=-4.01 T=  6828 logg=2.89
Changing to met=-2.50 for met=-4.01 T=  7022 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  7220 logg=2.95
Changing to met=-2.50 for met=-4.01 T=  7411 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  7607 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  7808 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  8014 logg=3.06
Changing to met=-2.50 for met=-4.01 T=  8226 logg=3.08
Changing to met=-2.50 for met=-4.01 T=  8444 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  8667 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  8896 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  9135 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  9381 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  9634 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  9892 logg=3.29
Changing to met=-2.50 for met=-4.01 T= 10142 logg=3.31
Changing to met=-2.50 for met=-4.01 T= 10397 logg=3.34
Changing to met=-2.50 for met=-4.01 T= 10657 logg=3.37
Changing to met=-2.50 for met=-4.01 T= 10925 logg=3.40
Changing to met=-2.50 for met=-4.01 T= 11199 logg=3.42
Changing to met=-2.50 for met=-4.01 T= 11479 logg=3.45
Changing to met=-2.50 for met=-4.01 T= 11767 logg=3.48
Changing to met=-2.50 for met=-4.01 T= 12064 logg=3.51
Changing to met=-2.50 for met=-4.01 T= 12369 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 12683 logg=3.56
Changing to met=-2.50 for met=-4.01 T= 13004 logg=3.59
Changing to met=-2.50 for met=-4.01 T= 13341 logg=3.62
Changing to met=-2.50 for met=-4.01 T= 13688 logg=3.65
Changing to met=-2.50 for met=-4.01 T= 14044 logg=3.68
Changing to met=-2.50 for met=-4.01 T= 14407 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 14777 logg=3.74
Changing to met=-2.50 for met=-4.01 T= 15156 logg=3.77
Changing to met=-2.50 for met=-4.01 T= 15548 logg=3.80
Changing to met=-2.50 for met=-4.01 T= 15952 logg=3.83
Changing to met=-2.50 for met=-4.01 T= 16367 logg=3.86
Changing to met=-2.50 for met=-4.01 T= 16761 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 17159 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 17566 logg=3.94
Changing to met=-2.50 for met=-4.01 T= 19281 logg=4.04
Changing to met=-2.50 for met=-4.01 T= 21230 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 21599 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 18388 logg=3.92
Changing to met=-2.50 for met=-4.01 T= 18698 logg=3.95
Changing to met=-2.50 for met=-4.01 T= 23782 logg=4.29
Changing to met=-2.50 for met=-4.01 T= 24407 logg=4.32
Changing to met=-2.50 for met=-4.01 T= 25047 logg=4.34
Changing to met=-2.50 for met=-4.01 T= 25703 logg=4.37
Changing to met=-2.50 for met=-4.01 T= 26375 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 27064 logg=4.43
Changing to met=-2.50 for met=-4.01 T= 27770 logg=4.46
Changing to met=-2.50 for met=-4.01 T= 28494 logg=4.49
Changing to met=-2.50 for met=-4.01 T= 29226 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 29962 logg=4.54
Changing to met=-2.50 for met=-4.01 T= 30717 logg=4.57
Changing to met=-2.50 for met=-4.01 T= 31486 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 32261 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 33056 logg=4.64
Changing to met=-2.50 for met=-4.01 T= 33873 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 34710 logg=4.70
Changing to met=-2.50 for met=-4.01 T= 35564 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 36414 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 37143 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 37690 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 38034 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 37719 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 37058 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 36748 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 37236 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 37596 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38035 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38545 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39091 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39425 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39722 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40008 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40297 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40589 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40887 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41190 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41497 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41808 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42126 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42525 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42916 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43306 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43663 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44012 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44380 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44917 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45436 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45815 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46223 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46623 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47013 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47449 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47940 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48424 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48932 logg=4.79
Changing to logg=5.00 for T= 49440 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49440 logg=4.79
Changing to logg=5.00 for T= 49942 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49942 logg=4.78
Changing to T= 50000 for T= 50467 logg=4.78
Changing to logg=5.00 for T= 50467 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50467 logg=4.78
Changing to T= 50000 for T= 50989 logg=4.78
Changing to logg=5.00 for T= 50989 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50989 logg=4.78
Changing to T= 50000 for T= 51515 logg=4.78
Changing to logg=5.00 for T= 51515 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51515 logg=4.78
Changing to T= 50000 for T= 52053 logg=4.78
Changing to logg=5.00 for T= 52053 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52053 logg=4.78
Changing to T= 50000 for T= 52591 logg=4.78
Changing to logg=5.00 for T= 52591 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52591 logg=4.78
Changing to T= 50000 for T= 53140 logg=4.77
Changing to logg=5.00 for T= 53140 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53140 logg=4.77
Changing to T= 50000 for T= 53692 logg=4.77
Changing to logg=5.00 for T= 53692 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53692 logg=4.77
Changing to T= 50000 for T= 54252 logg=4.77
Changing to logg=5.00 for T= 54252 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54252 logg=4.77
Changing to T= 50000 for T= 54817 logg=4.77
Changing to logg=5.00 for T= 54817 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54817 logg=4.77
Changing to T= 50000 for T= 55390 logg=4.77
Changing to logg=5.00 for T= 55390 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55390 logg=4.77
Changing to T= 50000 for T= 55968 logg=4.77
Changing to logg=5.00 for T= 55968 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55968 logg=4.77
Changing to T= 50000 for T= 56471 logg=4.76
Changing to logg=5.00 for T= 56471 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56471 logg=4.76
Changing to T= 50000 for T= 56883 logg=4.76
Changing to logg=5.00 for T= 56883 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56883 logg=4.76
Changing to T= 50000 for T= 57351 logg=4.76
Changing to logg=5.00 for T= 57351 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57351 logg=4.76
Changing to T= 50000 for T= 58325 logg=4.76
Changing to logg=5.00 for T= 58325 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58325 logg=4.76
Changing to T= 50000 for T= 58769 logg=4.76
Changing to logg=5.00 for T= 58769 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58769 logg=4.76
Changing to T= 50000 for T= 59905 logg=4.75
Changing to logg=5.00 for T= 59905 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59905 logg=4.75
Changing to T= 50000 for T= 60260 logg=4.75
Changing to logg=5.00 for T= 60260 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60260 logg=4.75
Changing to T= 50000 for T= 60622 logg=4.75
Changing to logg=5.00 for T= 60622 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60622 logg=4.75
Changing to T= 50000 for T= 60986 logg=4.75
Changing to logg=5.00 for T= 60986 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60986 logg=4.75
Changing to T= 50000 for T= 61359 logg=4.75
Changing to logg=5.00 for T= 61359 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61359 logg=4.75
Changing to T= 50000 for T= 61745 logg=4.75
Changing to logg=5.00 for T= 61745 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61745 logg=4.75
Changing to T= 50000 for T= 62134 logg=4.75
Changing to logg=5.00 for T= 62134 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62134 logg=4.75
Changing to T= 50000 for T= 62523 logg=4.75
Changing to logg=5.00 for T= 62523 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62523 logg=4.75
Changing to T= 50000 for T= 62909 logg=4.74
Changing to logg=5.00 for T= 62909 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62909 logg=4.74
Changing to T= 50000 for T= 63334 logg=4.74
Changing to logg=5.00 for T= 63334 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63334 logg=4.74
Changing to T= 50000 for T= 63759 logg=4.74
Changing to logg=5.00 for T= 63759 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63759 logg=4.74
Changing to T= 50000 for T= 64180 logg=4.74
Changing to logg=5.00 for T= 64180 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64180 logg=4.74
Changing to T= 50000 for T= 64594 logg=4.74
Changing to logg=5.00 for T= 64594 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64594 logg=4.74
Changing to T= 50000 for T= 65311 logg=4.74
Changing to logg=5.00 for T= 65311 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65311 logg=4.74
Changing to T= 50000 for T= 66122 logg=4.74
Changing to logg=5.00 for T= 66122 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 66122 logg=4.74
Changing to T= 50000 for T= 66921 logg=4.73
Changing to logg=5.00 for T= 66921 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66921 logg=4.73
Changing to T= 50000 for T= 67772 logg=4.73
Changing to logg=5.00 for T= 67772 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67772 logg=4.73
Changing to T= 50000 for T= 68360 logg=4.73
Changing to logg=5.00 for T= 68360 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 68360 logg=4.73
Changing to T= 50000 for T= 70314 logg=4.67
Changing to logg=5.00 for T= 70314 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70314 logg=4.67
Changing to T= 50000 for T= 70718 logg=4.67
Changing to logg=5.00 for T= 70718 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70718 logg=4.67
Changing to T= 50000 for T= 72141 logg=4.67
Changing to logg=5.00 for T= 72141 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72141 logg=4.67
Changing to T= 50000 for T= 72369 logg=4.67
Changing to logg=5.00 for T= 72369 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72369 logg=4.67
Changing to T= 50000 for T= 72588 logg=4.67
Changing to logg=5.00 for T= 72588 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72588 logg=4.67
Changing to T= 50000 for T= 73503 logg=4.68
Changing to logg=5.00 for T= 73503 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 73503 logg=4.68
Changing to T= 50000 for T= 74346 logg=4.69
Changing to logg=5.00 for T= 74346 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74346 logg=4.69
Changing to T= 50000 for T= 74851 logg=4.69
Changing to logg=5.00 for T= 74851 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74851 logg=4.69
Changing to T= 50000 for T= 75399 logg=4.68
Changing to logg=5.00 for T= 75399 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75399 logg=4.68
Changing to T= 50000 for T= 75935 logg=4.68
Changing to logg=5.00 for T= 75935 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75935 logg=4.68
Isochrone generation took 5.396662 s.
Making photometry for isochrone: log(t) = 5.15  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:43.174605   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4132 K  m_2mass_J = 4.78
M =   3.986 Msun  T =  8896 K  m_2mass_J = -1.79
M =  31.579 Msun  T = 55968 K  m_2mass_J = -2.41
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4132 K  m_2mass_H = 4.27
M =   3.986 Msun  T =  8896 K  m_2mass_H = -1.81

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  31.579 Msun  T = 55968 K  m_2mass_H = -2.29
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4130 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4139 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4154 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4168 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4182 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4196 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4211 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4224 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4238 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4252 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4266 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4279 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4293 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4308 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4329 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4350 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4372 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4393 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4414 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4436 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4461 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4489 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4517 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4545 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4573 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4596 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4619 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4643 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4666 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4722 logg=3.28
Changing to met=-4.00 for met=-4.01 T=  4751 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4812 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4846 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4859 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4881 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4902 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  4948 logg=3.27
Changing to met=-4.00 for met=-4.01 T=  5000 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  5051 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5084 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5117 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5151 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5181 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5209 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5239 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5265 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5282 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5300 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5313 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5326 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5339 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5352 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5366 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5380 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5395 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5410 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5426 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5442 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5459 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5476 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5494 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5512 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5524 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5543 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5570 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5592 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5604 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5619 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5636 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5653 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5656 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5659 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5662 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5674 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5691 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5711 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5728 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5745 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5769 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  5781 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5789 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  5850 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5852 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  5927 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  6013 logg=2.99
Changing to met=-2.50 for met=-4.01 T=  6116 logg=2.95
Changing to met=-2.50 for met=-4.01 T=  6239 logg=2.93
Changing to met=-2.50 for met=-4.01 T=  6381 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  6540 logg=2.92
Changing to met=-2.50 for met=-4.01 T=  6712 logg=2.93
Changing to met=-2.50 for met=-4.01 T=  6895 logg=2.94
Changing to met=-2.50 for met=-4.01 T=  7088 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  7288 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  7492 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  7702 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  7912 logg=3.08
Changing to met=-2.50 for met=-4.01 T=  8121 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  8335 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  8556 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  8782 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  9014 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  9252 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  9497 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  9749 logg=3.31
Changing to met=-2.50 for met=-4.01 T= 10010 logg=3.34
Changing to met=-2.50 for met=-4.01 T= 10279 logg=3.37
Changing to met=-2.50 for met=-4.01 T= 10554 logg=3.40
Changing to met=-2.50 for met=-4.01 T= 10833 logg=3.43
Changing to met=-2.50 for met=-4.01 T= 11104 logg=3.45
Changing to met=-2.50 for met=-4.01 T= 11382 logg=3.48
Changing to met=-2.50 for met=-4.01 T= 11668 logg=3.51
Changing to met=-2.50 for met=-4.01 T= 11961 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 12261 logg=3.57
Changing to met=-2.50 for met=-4.01 T= 12568 logg=3.59
Changing to met=-2.50 for met=-4.01 T= 12884 logg=3.62
Changing to met=-2.50 for met=-4.01 T= 13209 logg=3.65
Changing to met=-2.50 for met=-4.01 T= 13543 logg=3.68
Changing to met=-2.50 for met=-4.01 T= 13885 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 14238 logg=3.73
Changing to met=-2.50 for met=-4.01 T= 14608 logg=3.76
Changing to met=-2.50 for met=-4.01 T= 14987 logg=3.79
Changing to met=-2.50 for met=-4.01 T= 15374 logg=3.82
Changing to met=-2.50 for met=-4.01 T= 15767 logg=3.85
Changing to met=-2.50 for met=-4.01 T= 16169 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 16581 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 17012 logg=3.94
Changing to met=-2.50 for met=-4.01 T= 17455 logg=3.97
Changing to met=-2.50 for met=-4.01 T= 17894 logg=4.00
Changing to met=-2.50 for met=-4.01 T= 18318 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 18751 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 20699 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 20852 logg=4.17
Changing to met=-2.50 for met=-4.01 T= 23373 logg=4.31
Changing to met=-2.50 for met=-4.01 T= 23771 logg=4.34
Changing to met=-2.50 for met=-4.01 T= 18971 logg=3.95
Changing to met=-2.50 for met=-4.01 T= 25452 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 26119 logg=4.43
Changing to met=-2.50 for met=-4.01 T= 26802 logg=4.46
Changing to met=-2.50 for met=-4.01 T= 27502 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 28221 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 28957 logg=4.54
Changing to met=-2.50 for met=-4.01 T= 29713 logg=4.57
Changing to met=-2.50 for met=-4.01 T= 30488 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 31273 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 32068 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 32891 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 33721 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 34555 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 35384 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 36130 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 36660 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 36954 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 36402 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 35769 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 35813 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 36141 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 36396 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 36701 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37177 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37778 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38151 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38477 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38811 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39150 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39493 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39785 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40078 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40368 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40670 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40969 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41277 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41584 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41897 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42244 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42630 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43026 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43411 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43761 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44114 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44545 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45084 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45555 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45949 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46353 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46745 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47152 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47608 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48088 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48595 logg=4.79
Changing to logg=5.00 for T= 49097 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49097 logg=4.79
Changing to logg=5.00 for T= 49601 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49601 logg=4.79
Changing to T= 50000 for T= 50120 logg=4.78
Changing to logg=5.00 for T= 50120 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50120 logg=4.78
Changing to T= 50000 for T= 50635 logg=4.78
Changing to logg=5.00 for T= 50635 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50635 logg=4.78
Changing to T= 50000 for T= 51165 logg=4.78
Changing to logg=5.00 for T= 51165 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51165 logg=4.78
Changing to T= 50000 for T= 51695 logg=4.78
Changing to logg=5.00 for T= 51695 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51695 logg=4.78
Changing to T= 50000 for T= 52233 logg=4.78
Changing to logg=5.00 for T= 52233 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52233 logg=4.78
Changing to T= 50000 for T= 52777 logg=4.77
Changing to logg=5.00 for T= 52777 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52777 logg=4.77
Changing to T= 50000 for T= 53326 logg=4.77
Changing to logg=5.00 for T= 53326 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53326 logg=4.77
Changing to T= 50000 for T= 53883 logg=4.77
Changing to logg=5.00 for T= 53883 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53883 logg=4.77
Changing to T= 50000 for T= 54445 logg=4.77
Changing to logg=5.00 for T= 54445 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54445 logg=4.77
Changing to T= 50000 for T= 55014 logg=4.77
Changing to logg=5.00 for T= 55014 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55014 logg=4.77
Changing to T= 50000 for T= 55588 logg=4.77
Changing to logg=5.00 for T= 55588 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55588 logg=4.77
Changing to T= 50000 for T= 56170 logg=4.76
Changing to logg=5.00 for T= 56170 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56170 logg=4.76
Changing to T= 50000 for T= 56617 logg=4.76
Changing to logg=5.00 for T= 56617 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56617 logg=4.76
Changing to T= 50000 for T= 57036 logg=4.76
Changing to logg=5.00 for T= 57036 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57036 logg=4.76
Changing to T= 50000 for T= 57798 logg=4.76
Changing to logg=5.00 for T= 57798 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57798 logg=4.76
Changing to T= 50000 for T= 58493 logg=4.76
Changing to logg=5.00 for T= 58493 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58493 logg=4.76
Changing to T= 50000 for T= 58944 logg=4.76
Changing to logg=5.00 for T= 58944 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58944 logg=4.76
Changing to T= 50000 for T= 60044 logg=4.75
Changing to logg=5.00 for T= 60044 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60044 logg=4.75
Changing to T= 50000 for T= 60410 logg=4.75
Changing to logg=5.00 for T= 60410 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60410 logg=4.75
Changing to T= 50000 for T= 60782 logg=4.75
Changing to logg=5.00 for T= 60782 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60782 logg=4.75
Changing to T= 50000 for T= 61158 logg=4.75
Changing to logg=5.00 for T= 61158 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61158 logg=4.75
Changing to T= 50000 for T= 61534 logg=4.75
Changing to logg=5.00 for T= 61534 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61534 logg=4.75
Changing to T= 50000 for T= 61934 logg=4.75
Changing to logg=5.00 for T= 61934 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61934 logg=4.75
Changing to T= 50000 for T= 62338 logg=4.75
Changing to logg=5.00 for T= 62338 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 62338 logg=4.75
Changing to T= 50000 for T= 62743 logg=4.74
Changing to logg=5.00 for T= 62743 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62743 logg=4.74
Changing to T= 50000 for T= 63144 logg=4.74
Changing to logg=5.00 for T= 63144 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63144 logg=4.74
Changing to T= 50000 for T= 63563 logg=4.74
Changing to logg=5.00 for T= 63563 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63563 logg=4.74
Changing to T= 50000 for T= 64009 logg=4.74
Changing to logg=5.00 for T= 64009 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64009 logg=4.74
Changing to T= 50000 for T= 64452 logg=4.74
Changing to logg=5.00 for T= 64452 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64452 logg=4.74
Changing to T= 50000 for T= 65052 logg=4.74
Changing to logg=5.00 for T= 65052 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65052 logg=4.74
Changing to T= 50000 for T= 65828 logg=4.74
Changing to logg=5.00 for T= 65828 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 65828 logg=4.74
Changing to T= 50000 for T= 66658 logg=4.73
Changing to logg=5.00 for T= 66658 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66658 logg=4.73
Changing to T= 50000 for T= 67457 logg=4.73
Changing to logg=5.00 for T= 67457 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67457 logg=4.73
Changing to T= 50000 for T= 68174 logg=4.73
Changing to logg=5.00 for T= 68174 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 68174 logg=4.73
Changing to T= 50000 for T= 70087 logg=4.67
Changing to logg=5.00 for T= 70087 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70087 logg=4.67
Changing to T= 50000 for T= 70506 logg=4.67
Changing to logg=5.00 for T= 70506 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70506 logg=4.67
Changing to T= 50000 for T= 70943 logg=4.67
Changing to logg=5.00 for T= 70943 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70943 logg=4.67
Changing to T= 50000 for T= 72219 logg=4.67
Changing to logg=5.00 for T= 72219 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72219 logg=4.67
Changing to T= 50000 for T= 72467 logg=4.67
Changing to logg=5.00 for T= 72467 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72467 logg=4.67
Changing to T= 50000 for T= 72955 logg=4.67
Changing to logg=5.00 for T= 72955 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72955 logg=4.67
Changing to T= 50000 for T= 74049 logg=4.68
Changing to logg=5.00 for T= 74049 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74049 logg=4.68
Changing to T= 50000 for T= 74555 logg=4.69
Changing to logg=5.00 for T= 74555 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74555 logg=4.69
Changing to T= 50000 for T= 75121 logg=4.68
Changing to logg=5.00 for T= 75121 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75121 logg=4.68
Changing to T= 50000 for T= 75692 logg=4.68
Changing to logg=5.00 for T= 75692 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75692 logg=4.68
Isochrone generation took 5.284394 s.
Making photometry for isochrone: log(t) = 5.20  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:48.794634   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4130 K  m_2mass_J = 4.84
M =   3.861 Msun  T =  9014 K  m_2mass_J = -1.64
M =  30.288 Msun  T = 55014 K  m_2mass_J = -2.35
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4130 K  m_2mass_H = 4.33

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =   3.861 Msun  T =  9014 K  m_2mass_H = -1.66
M =  30.288 Msun  T = 55014 K  m_2mass_H = -2.23
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4128 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4138 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4152 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4166 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4181 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4195 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4209 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4223 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4236 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4250 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4264 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4277 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4291 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4307 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4328 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4349 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4370 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4392 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4413 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4435 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4461 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4488 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4516 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4544 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4572 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4595 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4618 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4641 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4664 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4720 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4748 logg=3.29
Changing to met=-4.00 for met=-4.01 T=  4808 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4842 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4855 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4874 logg=3.30
Changing to met=-4.00 for met=-4.01 T=  4896 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4934 logg=3.31
Changing to met=-4.00 for met=-4.01 T=  4982 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5031 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5070 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5103 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  5136 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5169 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5198 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5228 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5258 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5277 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5295 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5310 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5323 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5336 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5350 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5364 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5378 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5393 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5409 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5425 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5441 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5458 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5475 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5493 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5511 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5526 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5542 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5565 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5585 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5609 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5625 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5637 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5659 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5667 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5670 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5673 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  5677 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  5691 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  5717 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5737 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5756 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5776 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5801 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5810 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  5831 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  5940 logg=3.08
Changing to met=-2.50 for met=-4.01 T=  5958 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  6027 logg=3.01
Changing to met=-2.50 for met=-4.01 T=  6143 logg=2.98
Changing to met=-2.50 for met=-4.01 T=  6279 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  6432 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  6599 logg=2.97
Changing to met=-2.50 for met=-4.01 T=  6776 logg=2.98
Changing to met=-2.50 for met=-4.01 T=  6962 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  7156 logg=3.02
Changing to met=-2.50 for met=-4.01 T=  7356 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  7563 logg=3.08
Changing to met=-2.50 for met=-4.01 T=  7775 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  7992 logg=3.13
Changing to met=-2.50 for met=-4.01 T=  8215 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  8443 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  8668 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  8896 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  9131 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  9373 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  9620 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  9875 logg=3.36
Changing to met=-2.50 for met=-4.01 T= 10136 logg=3.39
Changing to met=-2.50 for met=-4.01 T= 10404 logg=3.42
Changing to met=-2.50 for met=-4.01 T= 10681 logg=3.45
Changing to met=-2.50 for met=-4.01 T= 10967 logg=3.48
Changing to met=-2.50 for met=-4.01 T= 11260 logg=3.51
Changing to met=-2.50 for met=-4.01 T= 11560 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 11859 logg=3.57
Changing to met=-2.50 for met=-4.01 T= 12156 logg=3.59
Changing to met=-2.50 for met=-4.01 T= 12461 logg=3.62
Changing to met=-2.50 for met=-4.01 T= 12773 logg=3.65
Changing to met=-2.50 for met=-4.01 T= 13094 logg=3.68
Changing to met=-2.50 for met=-4.01 T= 13423 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 13760 logg=3.73
Changing to met=-2.50 for met=-4.01 T= 14106 logg=3.76
Changing to met=-2.50 for met=-4.01 T= 14462 logg=3.79
Changing to met=-2.50 for met=-4.01 T= 14827 logg=3.82
Changing to met=-2.50 for met=-4.01 T= 15201 logg=3.85
Changing to met=-2.50 for met=-4.01 T= 15591 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 15994 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 16407 logg=3.93
Changing to met=-2.50 for met=-4.01 T= 16827 logg=3.96
Changing to met=-2.50 for met=-4.01 T= 17254 logg=3.99
Changing to met=-2.50 for met=-4.01 T= 17690 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 18145 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 18619 logg=4.08
Changing to met=-2.50 for met=-4.01 T= 19105 logg=4.11
Changing to met=-2.50 for met=-4.01 T= 19560 logg=4.14
Changing to met=-2.50 for met=-4.01 T= 20023 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 22174 logg=4.28
Changing to met=-2.50 for met=-4.01 T= 22332 logg=4.29
Changing to met=-2.50 for met=-4.01 T= 25207 logg=4.43
Changing to met=-2.50 for met=-4.01 T= 25868 logg=4.46
Changing to met=-2.50 for met=-4.01 T= 26546 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 27241 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 27953 logg=4.54
Changing to met=-2.50 for met=-4.01 T= 28685 logg=4.57
Changing to met=-2.50 for met=-4.01 T= 29436 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 30207 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 31002 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 31821 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 32666 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 33510 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 34356 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 35108 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 35619 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 35901 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35355 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 34732 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 34809 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 35094 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 35325 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 35618 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35992 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36425 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36721 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37087 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37462 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37850 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38221 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38556 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38897 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39231 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39572 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39861 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40153 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40452 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40750 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41054 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41361 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41673 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41990 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42350 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42737 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43144 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43511 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43856 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44227 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44709 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45254 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45677 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46078 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46474 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46879 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47283 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47758 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48259 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48752 logg=4.79
Changing to logg=5.00 for T= 49263 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49263 logg=4.79
Changing to logg=5.00 for T= 49772 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49772 logg=4.78
Changing to T= 50000 for T= 50290 logg=4.78
Changing to logg=5.00 for T= 50290 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50290 logg=4.78
Changing to T= 50000 for T= 50813 logg=4.78
Changing to logg=5.00 for T= 50813 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50813 logg=4.78
Changing to T= 50000 for T= 51340 logg=4.78
Changing to logg=5.00 for T= 51340 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51340 logg=4.78
Changing to T= 50000 for T= 51876 logg=4.78
Changing to logg=5.00 for T= 51876 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51876 logg=4.78
Changing to T= 50000 for T= 52415 logg=4.78
Changing to logg=5.00 for T= 52415 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52415 logg=4.78
Changing to T= 50000 for T= 52963 logg=4.77
Changing to logg=5.00 for T= 52963 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52963 logg=4.77
Changing to T= 50000 for T= 53515 logg=4.77
Changing to logg=5.00 for T= 53515 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53515 logg=4.77
Changing to T= 50000 for T= 54074 logg=4.77
Changing to logg=5.00 for T= 54074 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54074 logg=4.77
Changing to T= 50000 for T= 54639 logg=4.77
Changing to logg=5.00 for T= 54639 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54639 logg=4.77
Changing to T= 50000 for T= 55211 logg=4.77
Changing to logg=5.00 for T= 55211 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 55211 logg=4.77
Changing to T= 50000 for T= 55789 logg=4.76
Changing to logg=5.00 for T= 55789 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55789 logg=4.76
Changing to T= 50000 for T= 56347 logg=4.76
Changing to logg=5.00 for T= 56347 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56347 logg=4.76
Changing to T= 50000 for T= 56767 logg=4.76
Changing to logg=5.00 for T= 56767 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56767 logg=4.76
Changing to T= 50000 for T= 57193 logg=4.76
Changing to logg=5.00 for T= 57193 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57193 logg=4.76
Changing to T= 50000 for T= 58212 logg=4.76
Changing to logg=5.00 for T= 58212 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 58212 logg=4.76
Changing to T= 50000 for T= 58665 logg=4.75
Changing to logg=5.00 for T= 58665 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58665 logg=4.75
Changing to T= 50000 for T= 59596 logg=4.75
Changing to logg=5.00 for T= 59596 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59596 logg=4.75
Changing to T= 50000 for T= 60189 logg=4.75
Changing to logg=5.00 for T= 60189 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60189 logg=4.75
Changing to T= 50000 for T= 60565 logg=4.75
Changing to logg=5.00 for T= 60565 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60565 logg=4.75
Changing to T= 50000 for T= 60950 logg=4.75
Changing to logg=5.00 for T= 60950 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60950 logg=4.75
Changing to T= 50000 for T= 61338 logg=4.75
Changing to logg=5.00 for T= 61338 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61338 logg=4.75
Changing to T= 50000 for T= 61727 logg=4.75
Changing to logg=5.00 for T= 61727 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61727 logg=4.75
Changing to T= 50000 for T= 62128 logg=4.74
Changing to logg=5.00 for T= 62128 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62128 logg=4.74
Changing to T= 50000 for T= 62550 logg=4.74
Changing to logg=5.00 for T= 62550 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62550 logg=4.74
Changing to T= 50000 for T= 62972 logg=4.74
Changing to logg=5.00 for T= 62972 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62972 logg=4.74
Changing to T= 50000 for T= 63393 logg=4.74
Changing to logg=5.00 for T= 63393 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63393 logg=4.74
Changing to T= 50000 for T= 63808 logg=4.74
Changing to logg=5.00 for T= 63808 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63808 logg=4.74
Changing to T= 50000 for T= 64263 logg=4.74
Changing to logg=5.00 for T= 64263 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64263 logg=4.74
Changing to T= 50000 for T= 64777 logg=4.74
Changing to logg=5.00 for T= 64777 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64777 logg=4.74
Changing to T= 50000 for T= 65573 logg=4.73
Changing to logg=5.00 for T= 65573 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 65573 logg=4.73
Changing to T= 50000 for T= 66387 logg=4.73
Changing to logg=5.00 for T= 66387 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66387 logg=4.73
Changing to T= 50000 for T= 67216 logg=4.73
Changing to logg=5.00 for T= 67216 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67216 logg=4.73
Changing to T= 50000 for T= 68011 logg=4.73
Changing to logg=5.00 for T= 68011 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 68011 logg=4.73
Changing to T= 50000 for T= 68508 logg=4.73
Changing to logg=5.00 for T= 68508 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 68508 logg=4.73
Changing to T= 50000 for T= 70257 logg=4.67
Changing to logg=5.00 for T= 70257 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70257 logg=4.67
Changing to T= 50000 for T= 70683 logg=4.67
Changing to logg=5.00 for T= 70683 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 70683 logg=4.67
Changing to T= 50000 for T= 72088 logg=4.67
Changing to logg=5.00 for T= 72088 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72088 logg=4.67
Changing to T= 50000 for T= 72319 logg=4.67
Changing to logg=5.00 for T= 72319 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72319 logg=4.67
Changing to T= 50000 for T= 72565 logg=4.67
Changing to logg=5.00 for T= 72565 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72565 logg=4.67
Changing to T= 50000 for T= 73600 logg=4.68
Changing to logg=5.00 for T= 73600 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 73600 logg=4.68
Changing to T= 50000 for T= 74324 logg=4.68
Changing to logg=5.00 for T= 74324 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74324 logg=4.68
Changing to T= 50000 for T= 74813 logg=4.69
Changing to logg=5.00 for T= 74813 logg=4.69
Changing to met=-2.50 for met=-4.01 T= 74813 logg=4.69
Changing to T= 50000 for T= 75354 logg=4.68
Changing to logg=5.00 for T= 75354 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75354 logg=4.68
Changing to T= 50000 for T= 75951 logg=4.67
Changing to logg=5.00 for T= 75951 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75951 logg=4.67
Isochrone generation took 5.372088 s.
Making photometry for isochrone: log(t) = 5.25  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:29:54.504111   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4128 K  m_2mass_J = 4.89
M =   3.736 Msun  T =  9131 K  m_2mass_J = -1.49

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  28.993 Msun  T = 54074 K  m_2mass_J = -2.29
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4128 K  m_2mass_H = 4.39
M =   3.736 Msun  T =  9131 K  m_2mass_H = -1.51
M =  28.993 Msun  T = 54074 K  m_2mass_H = -2.17
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4126 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4137 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4151 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4165 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4179 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4194 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4207 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4221 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4235 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4249 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4262 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4276 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4290 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4306 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4327 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4348 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4369 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4391 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4413 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4434 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4460 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4487 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4515 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4543 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4571 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4593 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4616 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4639 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4661 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4715 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4743 logg=3.32
Changing to met=-4.00 for met=-4.01 T=  4798 logg=3.33
Changing to met=-4.00 for met=-4.01 T=  4835 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4847 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4864 logg=3.34
Changing to met=-4.00 for met=-4.01 T=  4886 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4904 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4959 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5008 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5054 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5087 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5122 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5157 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  5186 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5216 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5247 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5271 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5289 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5306 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5319 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5333 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5347 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5361 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5376 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5391 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5406 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5422 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5439 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5456 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5474 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5492 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5510 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5529 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5542 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5562 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5589 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5602 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  5631 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  5641 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  5662 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5678 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5681 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5684 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5687 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5700 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5722 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  5745 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  5766 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  5789 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5823 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5834 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5848 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  5901 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  6024 logg=3.04
Changing to met=-2.50 for met=-4.01 T=  6051 logg=3.02
Changing to met=-2.50 for met=-4.01 T=  6164 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  6315 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  6478 logg=3.00
Changing to met=-2.50 for met=-4.01 T=  6652 logg=3.01
Changing to met=-2.50 for met=-4.01 T=  6834 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  7024 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  7221 logg=3.07
Changing to met=-2.50 for met=-4.01 T=  7425 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  7633 logg=3.13
Changing to met=-2.50 for met=-4.01 T=  7847 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  8067 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  8292 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  8522 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  8759 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  9002 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  9249 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  9493 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  9744 logg=3.39
Changing to met=-2.50 for met=-4.01 T= 10001 logg=3.42
Changing to met=-2.50 for met=-4.01 T= 10266 logg=3.44
Changing to met=-2.50 for met=-4.01 T= 10537 logg=3.47
Changing to met=-2.50 for met=-4.01 T= 10816 logg=3.50
Changing to met=-2.50 for met=-4.01 T= 11103 logg=3.53
Changing to met=-2.50 for met=-4.01 T= 11397 logg=3.56
Changing to met=-2.50 for met=-4.01 T= 11701 logg=3.59
Changing to met=-2.50 for met=-4.01 T= 12013 logg=3.62
Changing to met=-2.50 for met=-4.01 T= 12333 logg=3.65
Changing to met=-2.50 for met=-4.01 T= 12661 logg=3.68
Changing to met=-2.50 for met=-4.01 T= 12981 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 13307 logg=3.73
Changing to met=-2.50 for met=-4.01 T= 13641 logg=3.76
Changing to met=-2.50 for met=-4.01 T= 13983 logg=3.79
Changing to met=-2.50 for met=-4.01 T= 14335 logg=3.82
Changing to met=-2.50 for met=-4.01 T= 14695 logg=3.85
Changing to met=-2.50 for met=-4.01 T= 15064 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 15444 logg=3.90
Changing to met=-2.50 for met=-4.01 T= 15833 logg=3.93
Changing to met=-2.50 for met=-4.01 T= 16232 logg=3.96
Changing to met=-2.50 for met=-4.01 T= 16643 logg=3.99
Changing to met=-2.50 for met=-4.01 T= 17072 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 17513 logg=4.05
Changing to met=-2.50 for met=-4.01 T= 17963 logg=4.08
Changing to met=-2.50 for met=-4.01 T= 18417 logg=4.10
Changing to met=-2.50 for met=-4.01 T= 18882 logg=4.13
Changing to met=-2.50 for met=-4.01 T= 19362 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 19869 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 25236 logg=4.55
Changing to met=-2.50 for met=-4.01 T= 21157 logg=4.25
Changing to met=-2.50 for met=-4.01 T= 21511 logg=4.28
Changing to met=-2.50 for met=-4.01 T= 23716 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 23879 logg=4.40
Changing to met=-2.50 for met=-4.01 T= 26984 logg=4.54
Changing to met=-2.50 for met=-4.01 T= 27692 logg=4.57
Changing to met=-2.50 for met=-4.01 T= 28419 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 29166 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 29935 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 30726 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 31543 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 32384 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 33234 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 34025 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 34575 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 34873 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 34360 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 33752 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 33801 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 34080 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 34305 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 34583 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 34939 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35361 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35630 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35902 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36176 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36460 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36792 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37179 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37563 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37950 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38314 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38646 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38981 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39326 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39644 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39935 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40234 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40531 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40830 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41138 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41448 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41764 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42079 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42451 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42853 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43256 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43610 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43958 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44337 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44874 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45415 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45799 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46203 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46606 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 47002 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47432 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47921 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48418 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48922 logg=4.79
Changing to logg=5.00 for T= 49428 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49428 logg=4.78
Changing to logg=5.00 for T= 49944 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49944 logg=4.78
Changing to T= 50000 for T= 50461 logg=4.78
Changing to logg=5.00 for T= 50461 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50461 logg=4.78
Changing to T= 50000 for T= 50988 logg=4.78
Changing to logg=5.00 for T= 50988 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50988 logg=4.78
Changing to T= 50000 for T= 51518 logg=4.78
Changing to logg=5.00 for T= 51518 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51518 logg=4.78
Changing to T= 50000 for T= 52056 logg=4.78
Changing to logg=5.00 for T= 52056 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 52056 logg=4.78
Changing to T= 50000 for T= 52600 logg=4.77
Changing to logg=5.00 for T= 52600 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52600 logg=4.77
Changing to T= 50000 for T= 53148 logg=4.77
Changing to logg=5.00 for T= 53148 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53148 logg=4.77
Changing to T= 50000 for T= 53705 logg=4.77
Changing to logg=5.00 for T= 53705 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53705 logg=4.77
Changing to T= 50000 for T= 54265 logg=4.77
Changing to logg=5.00 for T= 54265 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54265 logg=4.77
Changing to T= 50000 for T= 54834 logg=4.77
Changing to logg=5.00 for T= 54834 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54834 logg=4.77
Changing to T= 50000 for T= 55409 logg=4.76
Changing to logg=5.00 for T= 55409 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55409 logg=4.76
Changing to T= 50000 for T= 55990 logg=4.76
Changing to logg=5.00 for T= 55990 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55990 logg=4.76
Changing to T= 50000 for T= 56494 logg=4.76
Changing to logg=5.00 for T= 56494 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56494 logg=4.76
Changing to T= 50000 for T= 56921 logg=4.76
Changing to logg=5.00 for T= 56921 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56921 logg=4.76
Changing to T= 50000 for T= 57499 logg=4.76
Changing to logg=5.00 for T= 57499 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57499 logg=4.76
Changing to T= 50000 for T= 58382 logg=4.75
Changing to logg=5.00 for T= 58382 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58382 logg=4.75
Changing to T= 50000 for T= 58842 logg=4.75
Changing to logg=5.00 for T= 58842 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58842 logg=4.75
Changing to T= 50000 for T= 59965 logg=4.75
Changing to logg=5.00 for T= 59965 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59965 logg=4.75
Changing to T= 50000 for T= 60342 logg=4.75
Changing to logg=5.00 for T= 60342 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60342 logg=4.75
Changing to T= 50000 for T= 60727 logg=4.75
Changing to logg=5.00 for T= 60727 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60727 logg=4.75
Changing to T= 50000 for T= 61124 logg=4.75
Changing to logg=5.00 for T= 61124 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 61124 logg=4.75
Changing to T= 50000 for T= 61527 logg=4.74
Changing to logg=5.00 for T= 61527 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61527 logg=4.74
Changing to T= 50000 for T= 61932 logg=4.74
Changing to logg=5.00 for T= 61932 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61932 logg=4.74
Changing to T= 50000 for T= 62335 logg=4.74
Changing to logg=5.00 for T= 62335 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62335 logg=4.74
Changing to T= 50000 for T= 62766 logg=4.74
Changing to logg=5.00 for T= 62766 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62766 logg=4.74
Changing to T= 50000 for T= 63210 logg=4.74
Changing to logg=5.00 for T= 63210 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63210 logg=4.74
Changing to T= 50000 for T= 63652 logg=4.74
Changing to logg=5.00 for T= 63652 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63652 logg=4.74
Changing to T= 50000 for T= 64089 logg=4.74
Changing to logg=5.00 for T= 64089 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64089 logg=4.74
Changing to T= 50000 for T= 64519 logg=4.74
Changing to logg=5.00 for T= 64519 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64519 logg=4.74
Changing to T= 50000 for T= 65270 logg=4.73
Changing to logg=5.00 for T= 65270 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 65270 logg=4.73
Changing to T= 50000 for T= 66082 logg=4.73
Changing to logg=5.00 for T= 66082 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66082 logg=4.73
Changing to T= 50000 for T= 66931 logg=4.73
Changing to logg=5.00 for T= 66931 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66931 logg=4.73
Changing to T= 50000 for T= 67803 logg=4.73
Changing to logg=5.00 for T= 67803 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67803 logg=4.73
Changing to T= 50000 for T= 68366 logg=4.72
Changing to logg=5.00 for T= 68366 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68366 logg=4.72
Changing to T= 50000 for T= 68879 logg=4.72
Changing to logg=5.00 for T= 68879 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68879 logg=4.72
Changing to T= 50000 for T= 70481 logg=4.66
Changing to logg=5.00 for T= 70481 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70481 logg=4.66
Changing to T= 50000 for T= 70903 logg=4.66
Changing to logg=5.00 for T= 70903 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70903 logg=4.66
Changing to T= 50000 for T= 72182 logg=4.67
Changing to logg=5.00 for T= 72182 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72182 logg=4.67
Changing to T= 50000 for T= 72409 logg=4.67
Changing to logg=5.00 for T= 72409 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72409 logg=4.67
Changing to T= 50000 for T= 72907 logg=4.67
Changing to logg=5.00 for T= 72907 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72907 logg=4.67
Changing to T= 50000 for T= 74065 logg=4.68
Changing to logg=5.00 for T= 74065 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74065 logg=4.68
Changing to T= 50000 for T= 74578 logg=4.68
Changing to logg=5.00 for T= 74578 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74578 logg=4.68
Changing to T= 50000 for T= 75123 logg=4.68
Changing to logg=5.00 for T= 75123 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 75123 logg=4.68
Changing to T= 50000 for T= 75662 logg=4.67
Changing to logg=5.00 for T= 75662 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75662 logg=4.67
Isochrone generation took 5.482521 s.
Making photometry for isochrone: log(t) = 5.30  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:00.327915   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4126 K  m_2mass_J = 4.94
M =   3.611 Msun  T =  9249 K  m_2mass_J = -1.34
M =  27.695 Msun  T = 53148 K  m_2mass_J = -2.23
Starting filter: 2mass,H   Elapsed time: 0.18 seconds

Requested metallicity 1.3999999999999997e-06 is out of bounds.

Starting synthetic photometry
M =   0.100 Msun  T =  4126 K  m_2mass_H = 4.44
M =   3.611 Msun  T =  9249 K  m_2mass_H = -1.35
M =  27.695 Msun  T = 53148 K  m_2mass_H = -2.11
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4125 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4165 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4179 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4193 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4207 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4220 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4234 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4248 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4261 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4275 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4289 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4305 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4326 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4347 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4369 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4390 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4412 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4433 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4459 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4486 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4513 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4541 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4568 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4590 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4611 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4633 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4655 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4705 logg=3.35
Changing to met=-4.00 for met=-4.01 T=  4732 logg=3.36
Changing to met=-4.00 for met=-4.01 T=  4781 logg=3.37
Changing to met=-4.00 for met=-4.01 T=  4825 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4837 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4849 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4872 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4891 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4935 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4984 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5035 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5072 logg=3.44
Changing to met=-2.50 for met=-4.01 T=  5106 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  5142 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  5174 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5204 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5235 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5264 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5282 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5300 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5315 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5328 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5342 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5357 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5372 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5387 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5403 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5419 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5436 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5453 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5471 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5489 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5508 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5527 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5541 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5560 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5593 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5604 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  5630 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  5647 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  5662 logg=3.44
Changing to met=-2.50 for met=-4.01 T=  5688 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5692 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5695 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5698 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5702 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5719 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5752 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5776 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  5802 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5836 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  5861 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5876 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  5929 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  6022 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  6145 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  6194 logg=3.02
Changing to met=-2.50 for met=-4.01 T=  6355 logg=3.02
Changing to met=-2.50 for met=-4.01 T=  6527 logg=3.03
Changing to met=-2.50 for met=-4.01 T=  6707 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  6895 logg=3.07
Changing to met=-2.50 for met=-4.01 T=  7090 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  7289 logg=3.12
Changing to met=-2.50 for met=-4.01 T=  7494 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  7704 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  7919 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  8141 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  8368 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  8601 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  8841 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  9086 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  9338 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  9596 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  9862 logg=3.44
Changing to met=-2.50 for met=-4.01 T= 10128 logg=3.47
Changing to met=-2.50 for met=-4.01 T= 10395 logg=3.50
Changing to met=-2.50 for met=-4.01 T= 10670 logg=3.53
Changing to met=-2.50 for met=-4.01 T= 10952 logg=3.55
Changing to met=-2.50 for met=-4.01 T= 11242 logg=3.58
Changing to met=-2.50 for met=-4.01 T= 11540 logg=3.61
Changing to met=-2.50 for met=-4.01 T= 11846 logg=3.64
Changing to met=-2.50 for met=-4.01 T= 12161 logg=3.67
Changing to met=-2.50 for met=-4.01 T= 12484 logg=3.70
Changing to met=-2.50 for met=-4.01 T= 12816 logg=3.73
Changing to met=-2.50 for met=-4.01 T= 13157 logg=3.76
Changing to met=-2.50 for met=-4.01 T= 13507 logg=3.79
Changing to met=-2.50 for met=-4.01 T= 13862 logg=3.82
Changing to met=-2.50 for met=-4.01 T= 14210 logg=3.85
Changing to met=-2.50 for met=-4.01 T= 14567 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 14933 logg=3.90
Changing to met=-2.50 for met=-4.01 T= 15308 logg=3.93
Changing to met=-2.50 for met=-4.01 T= 15693 logg=3.96
Changing to met=-2.50 for met=-4.01 T= 16088 logg=3.99
Changing to met=-2.50 for met=-4.01 T= 16494 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 16910 logg=4.04
Changing to met=-2.50 for met=-4.01 T= 17336 logg=4.07
Changing to met=-2.50 for met=-4.01 T= 17774 logg=4.10
Changing to met=-2.50 for met=-4.01 T= 18229 logg=4.13
Changing to met=-2.50 for met=-4.01 T= 18701 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 19184 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 19670 logg=4.22
Changing to met=-2.50 for met=-4.01 T= 20164 logg=4.25
Changing to met=-2.50 for met=-4.01 T= 20668 logg=4.28
Changing to met=-2.50 for met=-4.01 T= 21210 logg=4.31
Changing to met=-2.50 for met=-4.01 T= 26049 logg=4.58
Changing to met=-2.50 for met=-4.01 T= 26503 logg=4.61
Changing to met=-2.50 for met=-4.01 T= 23164 logg=4.39
Changing to met=-2.50 for met=-4.01 T= 23547 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 25515 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 25683 logg=4.52
Changing to met=-2.50 for met=-4.01 T= 29670 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 30459 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 31273 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 32097 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 32880 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 33481 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 33826 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33408 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 32815 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 32776 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 33081 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 33311 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33591 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33944 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34348 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34605 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34867 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35137 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35418 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35692 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35977 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36253 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36539 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 36902 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37285 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37672 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38065 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38399 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38734 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39075 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39409 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39712 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40015 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40312 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40607 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40914 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41220 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41537 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41853 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42182 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42561 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42965 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43356 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43711 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44062 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44480 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45037 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45528 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45931 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46330 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46729 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47138 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47587 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48083 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48580 logg=4.79
Changing to logg=5.00 for T= 49087 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 49087 logg=4.79
Changing to logg=5.00 for T= 49597 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49597 logg=4.78
Changing to T= 50000 for T= 50114 logg=4.78
Changing to logg=5.00 for T= 50114 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50114 logg=4.78
Changing to T= 50000 for T= 50636 logg=4.78
Changing to logg=5.00 for T= 50636 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50636 logg=4.78
Changing to T= 50000 for T= 51163 logg=4.78
Changing to logg=5.00 for T= 51163 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51163 logg=4.78
Changing to T= 50000 for T= 51699 logg=4.78
Changing to logg=5.00 for T= 51699 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51699 logg=4.78
Changing to T= 50000 for T= 52237 logg=4.77
Changing to logg=5.00 for T= 52237 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52237 logg=4.77
Changing to T= 50000 for T= 52784 logg=4.77
Changing to logg=5.00 for T= 52784 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52784 logg=4.77
Changing to T= 50000 for T= 53336 logg=4.77
Changing to logg=5.00 for T= 53336 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53336 logg=4.77
Changing to T= 50000 for T= 53894 logg=4.77
Changing to logg=5.00 for T= 53894 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53894 logg=4.77
Changing to T= 50000 for T= 54460 logg=4.77
Changing to logg=5.00 for T= 54460 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54460 logg=4.77
Changing to T= 50000 for T= 55031 logg=4.76
Changing to logg=5.00 for T= 55031 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55031 logg=4.76
Changing to T= 50000 for T= 55608 logg=4.76
Changing to logg=5.00 for T= 55608 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55608 logg=4.76
Changing to T= 50000 for T= 56192 logg=4.76
Changing to logg=5.00 for T= 56192 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56192 logg=4.76
Changing to T= 50000 for T= 56645 logg=4.76
Changing to logg=5.00 for T= 56645 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56645 logg=4.76
Changing to T= 50000 for T= 57079 logg=4.76
Changing to logg=5.00 for T= 57079 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57079 logg=4.76
Changing to T= 50000 for T= 57945 logg=4.75
Changing to logg=5.00 for T= 57945 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 57945 logg=4.75
Changing to T= 50000 for T= 58555 logg=4.75
Changing to logg=5.00 for T= 58555 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58555 logg=4.75
Changing to T= 50000 for T= 59023 logg=4.75
Changing to logg=5.00 for T= 59023 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59023 logg=4.75
Changing to T= 50000 for T= 60115 logg=4.75
Changing to logg=5.00 for T= 60115 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60115 logg=4.75
Changing to T= 50000 for T= 60505 logg=4.75
Changing to logg=5.00 for T= 60505 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60505 logg=4.75
Changing to T= 50000 for T= 60897 logg=4.75
Changing to logg=5.00 for T= 60897 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60897 logg=4.75
Changing to T= 50000 for T= 61305 logg=4.74
Changing to logg=5.00 for T= 61305 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61305 logg=4.74
Changing to T= 50000 for T= 61723 logg=4.74
Changing to logg=5.00 for T= 61723 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61723 logg=4.74
Changing to T= 50000 for T= 62146 logg=4.74
Changing to logg=5.00 for T= 62146 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62146 logg=4.74
Changing to T= 50000 for T= 62568 logg=4.74
Changing to logg=5.00 for T= 62568 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62568 logg=4.74
Changing to T= 50000 for T= 62986 logg=4.74
Changing to logg=5.00 for T= 62986 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62986 logg=4.74
Changing to T= 50000 for T= 63451 logg=4.74
Changing to logg=5.00 for T= 63451 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63451 logg=4.74
Changing to T= 50000 for T= 63918 logg=4.74
Changing to logg=5.00 for T= 63918 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63918 logg=4.74
Changing to T= 50000 for T= 64382 logg=4.74
Changing to logg=5.00 for T= 64382 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 64382 logg=4.74
Changing to T= 50000 for T= 64973 logg=4.73
Changing to logg=5.00 for T= 64973 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64973 logg=4.73
Changing to T= 50000 for T= 65777 logg=4.73
Changing to logg=5.00 for T= 65777 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 65777 logg=4.73
Changing to T= 50000 for T= 66637 logg=4.73
Changing to logg=5.00 for T= 66637 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66637 logg=4.73
Changing to T= 50000 for T= 67452 logg=4.73
Changing to logg=5.00 for T= 67452 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 67452 logg=4.73
Changing to T= 50000 for T= 68181 logg=4.72
Changing to logg=5.00 for T= 68181 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68181 logg=4.72
Changing to T= 50000 for T= 68697 logg=4.72
Changing to logg=5.00 for T= 68697 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68697 logg=4.72
Changing to T= 50000 for T= 69228 logg=4.72
Changing to logg=5.00 for T= 69228 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 69228 logg=4.72
Changing to T= 50000 for T= 70695 logg=4.66
Changing to logg=5.00 for T= 70695 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70695 logg=4.66
Changing to T= 50000 for T= 72029 logg=4.66
Changing to logg=5.00 for T= 72029 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72029 logg=4.66
Changing to T= 50000 for T= 72276 logg=4.66
Changing to logg=5.00 for T= 72276 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72276 logg=4.66
Changing to T= 50000 for T= 72525 logg=4.67
Changing to logg=5.00 for T= 72525 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72525 logg=4.67
Changing to T= 50000 for T= 73541 logg=4.67
Changing to logg=5.00 for T= 73541 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 73541 logg=4.67
Changing to T= 50000 for T= 74264 logg=4.68
Changing to logg=5.00 for T= 74264 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74264 logg=4.68
Changing to T= 50000 for T= 74823 logg=4.68
Changing to logg=5.00 for T= 74823 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74823 logg=4.68
Changing to T= 50000 for T= 75402 logg=4.67
Changing to logg=5.00 for T= 75402 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75402 logg=4.67
Changing to T= 50000 for T= 75967 logg=4.67
Changing to logg=5.00 for T= 75967 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75967 logg=4.67
Isochrone generation took 5.550339 s.
Making photometry for isochrone: log(t) = 5.35  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:06.218482   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4125 K  m_2mass_J = 4.98
M =   3.490 Msun  T =  9338 K  m_2mass_J = -1.19
M =  26.395 Msun  T = 52237 K  m_2mass_J = -2.17
Starting filter: 2mass,H   Elapsed time: 0.19 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4125 K  m_2mass_H = 4.48
M =   3.490 Msun  T =  9338 K  m_2mass_H = -1.20

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  26.395 Msun  T = 52237 K  m_2mass_H = -2.05
      Time taken: 0.34 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4123 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4164 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4178 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4192 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4206 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4220 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4233 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4247 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4260 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4274 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4288 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4304 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4325 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4346 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4367 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4389 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4410 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4431 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4456 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4483 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4510 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4536 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4562 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4583 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4604 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4624 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4645 logg=3.38
Changing to met=-4.00 for met=-4.01 T=  4688 logg=3.39
Changing to met=-4.00 for met=-4.01 T=  4718 logg=3.40
Changing to met=-4.00 for met=-4.01 T=  4744 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4802 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4825 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4837 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4856 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4877 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4907 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4961 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5013 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5056 logg=3.48
Changing to met=-2.50 for met=-4.01 T=  5091 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5127 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5161 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5192 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5223 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5255 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5274 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5293 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5310 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5323 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5338 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5352 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5367 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5383 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5399 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5415 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5432 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5450 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5468 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5486 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5505 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5524 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5542 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5558 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5581 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5605 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5633 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5652 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5663 logg=3.48
Changing to met=-2.50 for met=-4.01 T=  5690 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5702 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5706 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5709 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5713 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5728 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5758 logg=3.44
Changing to met=-2.50 for met=-4.01 T=  5786 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  5815 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5848 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5892 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  5910 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  5952 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  6015 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  6131 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  6323 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  6405 logg=3.05
Changing to met=-2.50 for met=-4.01 T=  6584 logg=3.07
Changing to met=-2.50 for met=-4.01 T=  6770 logg=3.09
Changing to met=-2.50 for met=-4.01 T=  6961 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  7157 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  7357 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  7563 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  7775 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  7992 logg=3.25
Changing to met=-2.50 for met=-4.01 T=  8215 logg=3.28
Changing to met=-2.50 for met=-4.01 T=  8444 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  8679 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  8921 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  9169 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  9424 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  9685 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  9953 logg=3.49
Changing to met=-2.50 for met=-4.01 T= 10228 logg=3.52
Changing to met=-2.50 for met=-4.01 T= 10510 logg=3.55
Changing to met=-2.50 for met=-4.01 T= 10800 logg=3.58
Changing to met=-2.50 for met=-4.01 T= 11088 logg=3.61
Changing to met=-2.50 for met=-4.01 T= 11381 logg=3.64
Changing to met=-2.50 for met=-4.01 T= 11683 logg=3.67
Changing to met=-2.50 for met=-4.01 T= 11992 logg=3.69
Changing to met=-2.50 for met=-4.01 T= 12311 logg=3.72
Changing to met=-2.50 for met=-4.01 T= 12638 logg=3.75
Changing to met=-2.50 for met=-4.01 T= 12974 logg=3.78
Changing to met=-2.50 for met=-4.01 T= 13320 logg=3.81
Changing to met=-2.50 for met=-4.01 T= 13674 logg=3.84
Changing to met=-2.50 for met=-4.01 T= 14038 logg=3.87
Changing to met=-2.50 for met=-4.01 T= 14411 logg=3.90
Changing to met=-2.50 for met=-4.01 T= 14793 logg=3.93
Changing to met=-2.50 for met=-4.01 T= 15173 logg=3.96
Changing to met=-2.50 for met=-4.01 T= 15555 logg=3.99
Changing to met=-2.50 for met=-4.01 T= 15946 logg=4.02
Changing to met=-2.50 for met=-4.01 T= 16348 logg=4.04
Changing to met=-2.50 for met=-4.01 T= 16761 logg=4.07
Changing to met=-2.50 for met=-4.01 T= 17184 logg=4.10
Changing to met=-2.50 for met=-4.01 T= 17619 logg=4.13
Changing to met=-2.50 for met=-4.01 T= 18065 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 18522 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 18991 logg=4.22
Changing to met=-2.50 for met=-4.01 T= 19475 logg=4.25
Changing to met=-2.50 for met=-4.01 T= 19977 logg=4.28
Changing to met=-2.50 for met=-4.01 T= 20492 logg=4.31
Changing to met=-2.50 for met=-4.01 T= 21010 logg=4.34
Changing to met=-2.50 for met=-4.01 T= 21533 logg=4.36
Changing to met=-2.50 for met=-4.01 T= 22067 logg=4.39
Changing to met=-2.50 for met=-4.01 T= 22642 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 27917 logg=4.70
Changing to met=-2.50 for met=-4.01 T= 28398 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 24732 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 25142 logg=4.52
Changing to met=-2.50 for met=-4.01 T= 27213 logg=4.62
Changing to met=-2.50 for met=-4.01 T= 27379 logg=4.63
Changing to met=-2.50 for met=-4.01 T= 31773 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 32398 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 32780 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 32553 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 31974 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 31765 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 32068 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 32309 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 32591 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 32957 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33376 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33625 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33879 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34139 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34409 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34677 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34956 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35230 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35510 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35786 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36063 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36343 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36624 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37011 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37394 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37780 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38158 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38487 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38827 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39160 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39486 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39792 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40092 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40389 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40685 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40997 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41306 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41625 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41944 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42290 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42669 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43072 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43456 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43813 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44170 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44641 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45195 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45659 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46056 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46453 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 46860 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47270 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47746 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48244 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48746 logg=4.79
Changing to logg=5.00 for T= 49252 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49252 logg=4.78
Changing to logg=5.00 for T= 49768 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49768 logg=4.78
Changing to T= 50000 for T= 50283 logg=4.78
Changing to logg=5.00 for T= 50283 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50283 logg=4.78
Changing to T= 50000 for T= 50811 logg=4.78
Changing to logg=5.00 for T= 50811 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50811 logg=4.78
Changing to T= 50000 for T= 51341 logg=4.78
Changing to logg=5.00 for T= 51341 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 51341 logg=4.78
Changing to T= 50000 for T= 51877 logg=4.77
Changing to logg=5.00 for T= 51877 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51877 logg=4.77
Changing to T= 50000 for T= 52421 logg=4.77
Changing to logg=5.00 for T= 52421 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52421 logg=4.77
Changing to T= 50000 for T= 52970 logg=4.77
Changing to logg=5.00 for T= 52970 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52970 logg=4.77
Changing to T= 50000 for T= 53524 logg=4.77
Changing to logg=5.00 for T= 53524 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53524 logg=4.77
Changing to T= 50000 for T= 54086 logg=4.77
Changing to logg=5.00 for T= 54086 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 54086 logg=4.77
Changing to T= 50000 for T= 54654 logg=4.76
Changing to logg=5.00 for T= 54654 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54654 logg=4.76
Changing to T= 50000 for T= 55228 logg=4.76
Changing to logg=5.00 for T= 55228 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55228 logg=4.76
Changing to T= 50000 for T= 55808 logg=4.76
Changing to logg=5.00 for T= 55808 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55808 logg=4.76
Changing to T= 50000 for T= 56364 logg=4.76
Changing to logg=5.00 for T= 56364 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56364 logg=4.76
Changing to T= 50000 for T= 56800 logg=4.76
Changing to logg=5.00 for T= 56800 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56800 logg=4.76
Changing to T= 50000 for T= 57242 logg=4.76
Changing to logg=5.00 for T= 57242 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 57242 logg=4.76
Changing to T= 50000 for T= 58265 logg=4.75
Changing to logg=5.00 for T= 58265 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58265 logg=4.75
Changing to T= 50000 for T= 58734 logg=4.75
Changing to logg=5.00 for T= 58734 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58734 logg=4.75
Changing to T= 50000 for T= 59877 logg=4.75
Changing to logg=5.00 for T= 59877 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 59877 logg=4.75
Changing to T= 50000 for T= 60272 logg=4.75
Changing to logg=5.00 for T= 60272 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 60272 logg=4.75
Changing to T= 50000 for T= 60675 logg=4.74
Changing to logg=5.00 for T= 60675 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60675 logg=4.74
Changing to T= 50000 for T= 61082 logg=4.74
Changing to logg=5.00 for T= 61082 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61082 logg=4.74
Changing to T= 50000 for T= 61490 logg=4.74
Changing to logg=5.00 for T= 61490 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61490 logg=4.74
Changing to T= 50000 for T= 61925 logg=4.74
Changing to logg=5.00 for T= 61925 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61925 logg=4.74
Changing to T= 50000 for T= 62367 logg=4.74
Changing to logg=5.00 for T= 62367 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62367 logg=4.74
Changing to T= 50000 for T= 62810 logg=4.74
Changing to logg=5.00 for T= 62810 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62810 logg=4.74
Changing to T= 50000 for T= 63251 logg=4.74
Changing to logg=5.00 for T= 63251 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63251 logg=4.74
Changing to T= 50000 for T= 63692 logg=4.74
Changing to logg=5.00 for T= 63692 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 63692 logg=4.74
Changing to T= 50000 for T= 64188 logg=4.73
Changing to logg=5.00 for T= 64188 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64188 logg=4.73
Changing to T= 50000 for T= 64705 logg=4.73
Changing to logg=5.00 for T= 64705 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64705 logg=4.73
Changing to T= 50000 for T= 65522 logg=4.73
Changing to logg=5.00 for T= 65522 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 65522 logg=4.73
Changing to T= 50000 for T= 66357 logg=4.73
Changing to logg=5.00 for T= 66357 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66357 logg=4.73
Changing to T= 50000 for T= 67215 logg=4.72
Changing to logg=5.00 for T= 67215 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 67215 logg=4.72
Changing to T= 50000 for T= 68003 logg=4.72
Changing to logg=5.00 for T= 68003 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68003 logg=4.72
Changing to T= 50000 for T= 68508 logg=4.72
Changing to logg=5.00 for T= 68508 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68508 logg=4.72
Changing to T= 50000 for T= 69033 logg=4.72
Changing to logg=5.00 for T= 69033 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 69033 logg=4.72
Changing to T= 50000 for T= 70421 logg=4.66
Changing to logg=5.00 for T= 70421 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70421 logg=4.66
Changing to T= 50000 for T= 70923 logg=4.66
Changing to logg=5.00 for T= 70923 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70923 logg=4.66
Changing to T= 50000 for T= 72137 logg=4.66
Changing to logg=5.00 for T= 72137 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72137 logg=4.66
Changing to T= 50000 for T= 72383 logg=4.66
Changing to logg=5.00 for T= 72383 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72383 logg=4.66
Changing to T= 50000 for T= 72964 logg=4.67
Changing to logg=5.00 for T= 72964 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 72964 logg=4.67
Changing to T= 50000 for T= 74064 logg=4.67
Changing to logg=5.00 for T= 74064 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74064 logg=4.67
Changing to T= 50000 for T= 74560 logg=4.68
Changing to logg=5.00 for T= 74560 logg=4.68
Changing to met=-2.50 for met=-4.01 T= 74560 logg=4.68
Changing to T= 50000 for T= 75080 logg=4.67
Changing to logg=5.00 for T= 75080 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75080 logg=4.67
Changing to T= 50000 for T= 75647 logg=4.67
Changing to logg=5.00 for T= 75647 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75647 logg=4.67
Isochrone generation took 5.529302 s.
Making photometry for isochrone: log(t) = 5.40  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:12.094147   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4123 K  m_2mass_J = 5.01
M =   3.374 Msun  T =  9424 K  m_2mass_J = -1.04
M =  25.095 Msun  T = 51341 K  m_2mass_J = -2.10
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4123 K  m_2mass_H = 4.51

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =   3.374 Msun  T =  9424 K  m_2mass_H = -1.05
M =  25.095 Msun  T = 51341 K  m_2mass_H = -1.98
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4122 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4164 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4178 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4192 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4205 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4219 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4232 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4246 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4259 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4273 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4286 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4303 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4324 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4345 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4365 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4386 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4407 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4428 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4452 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4478 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4503 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4528 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4552 logg=3.41
Changing to met=-4.00 for met=-4.01 T=  4572 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4591 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4610 logg=3.42
Changing to met=-4.00 for met=-4.01 T=  4630 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4649 logg=3.43
Changing to met=-4.00 for met=-4.01 T=  4699 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4722 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4776 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4813 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4825 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4839 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4863 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4881 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4937 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4990 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5039 logg=3.52
Changing to met=-2.50 for met=-4.01 T=  5075 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5111 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5148 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5178 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5210 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5242 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5266 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5285 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5303 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5317 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5332 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5347 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5362 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5378 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5394 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5411 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5428 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5445 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5463 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5482 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5501 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5521 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5540 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5554 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5576 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5609 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5622 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5649 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5668 logg=3.52
Changing to met=-2.50 for met=-4.01 T=  5692 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5713 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  5717 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5721 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5724 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5739 logg=3.49
Changing to met=-2.50 for met=-4.01 T=  5757 logg=3.48
Changing to met=-2.50 for met=-4.01 T=  5796 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5827 logg=3.44
Changing to met=-2.50 for met=-4.01 T=  5866 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  5928 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  5951 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  5977 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  6046 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  6131 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  6286 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  6581 logg=3.10
Changing to met=-2.50 for met=-4.01 T=  6684 logg=3.11
Changing to met=-2.50 for met=-4.01 T=  6835 logg=3.13
Changing to met=-2.50 for met=-4.01 T=  7027 logg=3.16
Changing to met=-2.50 for met=-4.01 T=  7224 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  7426 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  7633 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  7846 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  8065 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  8290 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  8520 logg=3.36
Changing to met=-2.50 for met=-4.01 T=  8757 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  9001 logg=3.42
Changing to met=-2.50 for met=-4.01 T=  9251 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  9508 logg=3.48
Changing to met=-2.50 for met=-4.01 T=  9772 logg=3.51
Changing to met=-2.50 for met=-4.01 T= 10043 logg=3.54
Changing to met=-2.50 for met=-4.01 T= 10322 logg=3.57
Changing to met=-2.50 for met=-4.01 T= 10607 logg=3.60
Changing to met=-2.50 for met=-4.01 T= 10900 logg=3.63
Changing to met=-2.50 for met=-4.01 T= 11200 logg=3.66
Changing to met=-2.50 for met=-4.01 T= 11509 logg=3.69
Changing to met=-2.50 for met=-4.01 T= 11825 logg=3.72
Changing to met=-2.50 for met=-4.01 T= 12138 logg=3.75
Changing to met=-2.50 for met=-4.01 T= 12460 logg=3.78
Changing to met=-2.50 for met=-4.01 T= 12791 logg=3.81
Changing to met=-2.50 for met=-4.01 T= 13132 logg=3.83
Changing to met=-2.50 for met=-4.01 T= 13481 logg=3.86
Changing to met=-2.50 for met=-4.01 T= 13841 logg=3.89
Changing to met=-2.50 for met=-4.01 T= 14210 logg=3.92
Changing to met=-2.50 for met=-4.01 T= 14590 logg=3.95
Changing to met=-2.50 for met=-4.01 T= 14979 logg=3.98
Changing to met=-2.50 for met=-4.01 T= 15376 logg=4.01
Changing to met=-2.50 for met=-4.01 T= 15785 logg=4.04
Changing to met=-2.50 for met=-4.01 T= 16203 logg=4.07
Changing to met=-2.50 for met=-4.01 T= 16612 logg=4.10
Changing to met=-2.50 for met=-4.01 T= 17032 logg=4.13
Changing to met=-2.50 for met=-4.01 T= 17463 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 17906 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 18361 logg=4.22
Changing to met=-2.50 for met=-4.01 T= 18828 logg=4.25
Changing to met=-2.50 for met=-4.01 T= 19306 logg=4.28
Changing to met=-2.50 for met=-4.01 T= 19794 logg=4.30
Changing to met=-2.50 for met=-4.01 T= 20294 logg=4.33
Changing to met=-2.50 for met=-4.01 T= 20808 logg=4.36
Changing to met=-2.50 for met=-4.01 T= 21343 logg=4.39
Changing to met=-2.50 for met=-4.01 T= 21890 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 22442 logg=4.45
Changing to met=-2.50 for met=-4.01 T= 22997 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 23563 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 24176 logg=4.53
Changing to met=-2.50 for met=-4.01 T= 29768 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 30220 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 26421 logg=4.60
Changing to met=-2.50 for met=-4.01 T= 26855 logg=4.63
Changing to met=-2.50 for met=-4.01 T= 28703 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 31301 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 30724 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 30402 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 31076 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 31320 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 31593 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 31947 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32367 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32625 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32896 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 33172 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33433 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33693 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33963 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34230 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34504 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34780 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35053 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35330 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35598 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35876 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36151 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36418 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36740 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37118 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37498 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37885 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38240 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38580 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38914 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39242 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39561 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39868 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40169 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40468 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40766 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41080 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41391 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41714 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42036 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42402 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42777 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43173 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43553 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43911 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44281 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44799 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45379 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45782 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46179 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46585 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 46990 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47412 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47908 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48403 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48911 logg=4.78
Changing to logg=5.00 for T= 49421 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49421 logg=4.78
Changing to logg=5.00 for T= 49935 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49935 logg=4.78
Changing to T= 50000 for T= 50459 logg=4.78
Changing to logg=5.00 for T= 50459 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50459 logg=4.78
Changing to T= 50000 for T= 50986 logg=4.78
Changing to logg=5.00 for T= 50986 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50986 logg=4.78
Changing to T= 50000 for T= 51518 logg=4.77
Changing to logg=5.00 for T= 51518 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51518 logg=4.77
Changing to T= 50000 for T= 52059 logg=4.77
Changing to logg=5.00 for T= 52059 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52059 logg=4.77
Changing to T= 50000 for T= 52605 logg=4.77
Changing to logg=5.00 for T= 52605 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52605 logg=4.77
Changing to T= 50000 for T= 53156 logg=4.77
Changing to logg=5.00 for T= 53156 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53156 logg=4.77
Changing to T= 50000 for T= 53714 logg=4.77
Changing to logg=5.00 for T= 53714 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53714 logg=4.77
Changing to T= 50000 for T= 54278 logg=4.76
Changing to logg=5.00 for T= 54278 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54278 logg=4.76
Changing to T= 50000 for T= 54849 logg=4.76
Changing to logg=5.00 for T= 54849 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54849 logg=4.76
Changing to T= 50000 for T= 55426 logg=4.76
Changing to logg=5.00 for T= 55426 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55426 logg=4.76
Changing to T= 50000 for T= 56009 logg=4.76
Changing to logg=5.00 for T= 56009 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56009 logg=4.76
Changing to T= 50000 for T= 56516 logg=4.76
Changing to logg=5.00 for T= 56516 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56516 logg=4.76
Changing to T= 50000 for T= 56960 logg=4.76
Changing to logg=5.00 for T= 56960 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56960 logg=4.76
Changing to T= 50000 for T= 57644 logg=4.75
Changing to logg=5.00 for T= 57644 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 57644 logg=4.75
Changing to T= 50000 for T= 58440 logg=4.75
Changing to logg=5.00 for T= 58440 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58440 logg=4.75
Changing to T= 50000 for T= 58917 logg=4.75
Changing to logg=5.00 for T= 58917 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58917 logg=4.75
Changing to T= 50000 for T= 60029 logg=4.74
Changing to logg=5.00 for T= 60029 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60029 logg=4.74
Changing to T= 50000 for T= 60437 logg=4.74
Changing to logg=5.00 for T= 60437 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60437 logg=4.74
Changing to T= 50000 for T= 60854 logg=4.74
Changing to logg=5.00 for T= 60854 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60854 logg=4.74
Changing to T= 50000 for T= 61277 logg=4.74
Changing to logg=5.00 for T= 61277 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61277 logg=4.74
Changing to T= 50000 for T= 61702 logg=4.74
Changing to logg=5.00 for T= 61702 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61702 logg=4.74
Changing to T= 50000 for T= 62130 logg=4.74
Changing to logg=5.00 for T= 62130 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62130 logg=4.74
Changing to T= 50000 for T= 62594 logg=4.74
Changing to logg=5.00 for T= 62594 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 62594 logg=4.74
Changing to T= 50000 for T= 63061 logg=4.73
Changing to logg=5.00 for T= 63061 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63061 logg=4.73
Changing to T= 50000 for T= 63527 logg=4.73
Changing to logg=5.00 for T= 63527 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63527 logg=4.73
Changing to T= 50000 for T= 63988 logg=4.73
Changing to logg=5.00 for T= 63988 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63988 logg=4.73
Changing to T= 50000 for T= 64454 logg=4.73
Changing to logg=5.00 for T= 64454 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64454 logg=4.73
Changing to T= 50000 for T= 65209 logg=4.73
Changing to logg=5.00 for T= 65209 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 65209 logg=4.73
Changing to T= 50000 for T= 66046 logg=4.73
Changing to logg=5.00 for T= 66046 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 66046 logg=4.73
Changing to T= 50000 for T= 66924 logg=4.72
Changing to logg=5.00 for T= 66924 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 66924 logg=4.72
Changing to T= 50000 for T= 67822 logg=4.72
Changing to logg=5.00 for T= 67822 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 67822 logg=4.72
Changing to T= 50000 for T= 68361 logg=4.72
Changing to logg=5.00 for T= 68361 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68361 logg=4.72
Changing to T= 50000 for T= 68875 logg=4.72
Changing to logg=5.00 for T= 68875 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68875 logg=4.72
Changing to T= 50000 for T= 69395 logg=4.71
Changing to logg=5.00 for T= 69395 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 69395 logg=4.71
Changing to T= 50000 for T= 70677 logg=4.66
Changing to logg=5.00 for T= 70677 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 70677 logg=4.66
Changing to T= 50000 for T= 72000 logg=4.66
Changing to logg=5.00 for T= 72000 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72000 logg=4.66
Changing to T= 50000 for T= 72251 logg=4.66
Changing to logg=5.00 for T= 72251 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72251 logg=4.66
Changing to T= 50000 for T= 72479 logg=4.66
Changing to logg=5.00 for T= 72479 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72479 logg=4.66
Changing to T= 50000 for T= 73584 logg=4.67
Changing to logg=5.00 for T= 73584 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 73584 logg=4.67
Changing to T= 50000 for T= 74316 logg=4.67
Changing to logg=5.00 for T= 74316 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74316 logg=4.67
Changing to T= 50000 for T= 74859 logg=4.67
Changing to logg=5.00 for T= 74859 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74859 logg=4.67
Changing to T= 50000 for T= 75410 logg=4.67
Changing to logg=5.00 for T= 75410 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75410 logg=4.67
Changing to T= 50000 for T= 75950 logg=4.66
Changing to logg=5.00 for T= 75950 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 75950 logg=4.66
Isochrone generation took 5.496903 s.
Making photometry for isochrone: log(t) = 5.45  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:17.928513   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4122 K  m_2mass_J = 5.04
M =   3.271 Msun  T =  9508 K  m_2mass_J = -0.90
M =  23.792 Msun  T = 50459 K  m_2mass_J = -2.04
Starting filter: 2mass,H   Elapsed time: 0.18 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4122 K  m_2mass_H = 4.54
M =   3.271 Msun  T =  9508 K  m_2mass_H = -0.91

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  23.792 Msun  T = 50459 K  m_2mass_H = -1.92
      Time taken: 0.33 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4122 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4122 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4164 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4178 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4191 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4205 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4218 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4232 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4245 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4258 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4271 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4285 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4301 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4321 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4342 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4362 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4383 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4403 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4423 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4445 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4469 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4492 logg=3.44
Changing to met=-4.00 for met=-4.01 T=  4515 logg=3.45
Changing to met=-4.00 for met=-4.01 T=  4537 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4557 logg=3.46
Changing to met=-4.00 for met=-4.01 T=  4575 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4594 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4613 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4632 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4679 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4706 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4754 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4801 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4813 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4824 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4848 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4867 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4914 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4967 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5022 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5058 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5095 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5132 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5165 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5196 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5228 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5257 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5276 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5295 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5311 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5325 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5340 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5356 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5372 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5388 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5405 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5422 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5440 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5459 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5477 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5497 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5516 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5537 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5553 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5573 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5598 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5622 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5652 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5673 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5688 logg=3.55
Changing to met=-2.50 for met=-4.01 T=  5724 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5728 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5732 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5736 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  5740 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5760 logg=3.52
Changing to met=-2.50 for met=-4.01 T=  5803 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5841 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  5886 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  5943 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  5998 logg=3.30
Changing to met=-2.50 for met=-4.01 T=  6028 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  6069 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  6177 logg=3.17
Changing to met=-2.50 for met=-4.01 T=  6306 logg=3.15
Changing to met=-2.50 for met=-4.01 T=  6517 logg=3.14
Changing to met=-2.50 for met=-4.01 T=  6914 logg=3.18
Changing to met=-2.50 for met=-4.01 T=  7033 logg=3.20
Changing to met=-2.50 for met=-4.01 T=  7156 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  7290 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  7494 logg=3.26
Changing to met=-2.50 for met=-4.01 T=  7703 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  7918 logg=3.32
Changing to met=-2.50 for met=-4.01 T=  8138 logg=3.35
Changing to met=-2.50 for met=-4.01 T=  8364 logg=3.38
Changing to met=-2.50 for met=-4.01 T=  8597 logg=3.41
Changing to met=-2.50 for met=-4.01 T=  8836 logg=3.44
Changing to met=-2.50 for met=-4.01 T=  9081 logg=3.47
Changing to met=-2.50 for met=-4.01 T=  9333 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  9592 logg=3.52
Changing to met=-2.50 for met=-4.01 T=  9858 logg=3.55
Changing to met=-2.50 for met=-4.01 T= 10132 logg=3.58
Changing to met=-2.50 for met=-4.01 T= 10413 logg=3.61
Changing to met=-2.50 for met=-4.01 T= 10701 logg=3.64
Changing to met=-2.50 for met=-4.01 T= 10998 logg=3.67
Changing to met=-2.50 for met=-4.01 T= 11303 logg=3.71
Changing to met=-2.50 for met=-4.01 T= 11615 logg=3.74
Changing to met=-2.50 for met=-4.01 T= 11935 logg=3.77
Changing to met=-2.50 for met=-4.01 T= 12264 logg=3.80
Changing to met=-2.50 for met=-4.01 T= 12602 logg=3.83
Changing to met=-2.50 for met=-4.01 T= 12945 logg=3.86
Changing to met=-2.50 for met=-4.01 T= 13289 logg=3.89
Changing to met=-2.50 for met=-4.01 T= 13642 logg=3.92
Changing to met=-2.50 for met=-4.01 T= 14006 logg=3.95
Changing to met=-2.50 for met=-4.01 T= 14380 logg=3.98
Changing to met=-2.50 for met=-4.01 T= 14765 logg=4.01
Changing to met=-2.50 for met=-4.01 T= 15160 logg=4.03
Changing to met=-2.50 for met=-4.01 T= 15567 logg=4.07
Changing to met=-2.50 for met=-4.01 T= 15986 logg=4.10
Changing to met=-2.50 for met=-4.01 T= 16411 logg=4.13
Changing to met=-2.50 for met=-4.01 T= 16849 logg=4.16
Changing to met=-2.50 for met=-4.01 T= 17298 logg=4.19
Changing to met=-2.50 for met=-4.01 T= 17748 logg=4.22
Changing to met=-2.50 for met=-4.01 T= 18198 logg=4.25
Changing to met=-2.50 for met=-4.01 T= 18661 logg=4.27
Changing to met=-2.50 for met=-4.01 T= 19135 logg=4.30
Changing to met=-2.50 for met=-4.01 T= 19622 logg=4.33
Changing to met=-2.50 for met=-4.01 T= 20121 logg=4.36
Changing to met=-2.50 for met=-4.01 T= 20632 logg=4.39
Changing to met=-2.50 for met=-4.01 T= 21153 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 21686 logg=4.45
Changing to met=-2.50 for met=-4.01 T= 22235 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 22805 logg=4.50
Changing to met=-2.50 for met=-4.01 T= 23390 logg=4.53
Changing to met=-2.50 for met=-4.01 T= 23977 logg=4.56
Changing to met=-2.50 for met=-4.01 T= 24567 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 25170 logg=4.61
Changing to met=-2.50 for met=-4.01 T= 30022 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 30158 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 30091 logg=4.90
Changing to met=-2.50 for met=-4.01 T= 28357 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 29248 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 30115 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 30362 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 30623 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 30958 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 31359 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 31614 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 31878 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32148 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32425 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32690 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32982 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33256 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33521 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33788 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34053 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34330 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34600 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34880 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35154 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35417 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35692 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35964 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36226 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36504 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 36846 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37221 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37606 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37985 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38331 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38668 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38999 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39325 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39633 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39943 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40247 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40549 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40846 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41164 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41474 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41801 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 42132 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42513 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42887 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43276 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43649 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 44014 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44399 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44972 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45505 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45907 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46308 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 46711 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47123 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47573 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48066 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48570 logg=4.78
Changing to logg=5.00 for T= 49077 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49077 logg=4.78
Changing to logg=5.00 for T= 49588 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49588 logg=4.78
Changing to T= 50000 for T= 50108 logg=4.78
Changing to logg=5.00 for T= 50108 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50108 logg=4.78
Changing to T= 50000 for T= 50633 logg=4.78
Changing to logg=5.00 for T= 50633 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50633 logg=4.78
Changing to T= 50000 for T= 51163 logg=4.77
Changing to logg=5.00 for T= 51163 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51163 logg=4.77
Changing to T= 50000 for T= 51698 logg=4.77
Changing to logg=5.00 for T= 51698 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51698 logg=4.77
Changing to T= 50000 for T= 52241 logg=4.77
Changing to logg=5.00 for T= 52241 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52241 logg=4.77
Changing to T= 50000 for T= 52790 logg=4.77
Changing to logg=5.00 for T= 52790 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52790 logg=4.77
Changing to T= 50000 for T= 53344 logg=4.77
Changing to logg=5.00 for T= 53344 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 53344 logg=4.77
Changing to T= 50000 for T= 53905 logg=4.76
Changing to logg=5.00 for T= 53905 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 53905 logg=4.76
Changing to T= 50000 for T= 54471 logg=4.76
Changing to logg=5.00 for T= 54471 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54471 logg=4.76
Changing to T= 50000 for T= 55045 logg=4.76
Changing to logg=5.00 for T= 55045 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55045 logg=4.76
Changing to T= 50000 for T= 55625 logg=4.76
Changing to logg=5.00 for T= 55625 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55625 logg=4.76
Changing to T= 50000 for T= 56211 logg=4.76
Changing to logg=5.00 for T= 56211 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 56211 logg=4.76
Changing to T= 50000 for T= 56672 logg=4.75
Changing to logg=5.00 for T= 56672 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 56672 logg=4.75
Changing to T= 50000 for T= 57124 logg=4.75
Changing to logg=5.00 for T= 57124 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 57124 logg=4.75
Changing to T= 50000 for T= 58088 logg=4.75
Changing to logg=5.00 for T= 58088 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58088 logg=4.75
Changing to T= 50000 for T= 58620 logg=4.75
Changing to logg=5.00 for T= 58620 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58620 logg=4.75
Changing to T= 50000 for T= 59481 logg=4.74
Changing to logg=5.00 for T= 59481 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 59481 logg=4.74
Changing to T= 50000 for T= 60191 logg=4.74
Changing to logg=5.00 for T= 60191 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60191 logg=4.74
Changing to T= 50000 for T= 60606 logg=4.74
Changing to logg=5.00 for T= 60606 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60606 logg=4.74
Changing to T= 50000 for T= 61039 logg=4.74
Changing to logg=5.00 for T= 61039 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61039 logg=4.74
Changing to T= 50000 for T= 61480 logg=4.74
Changing to logg=5.00 for T= 61480 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61480 logg=4.74
Changing to T= 50000 for T= 61925 logg=4.74
Changing to logg=5.00 for T= 61925 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61925 logg=4.74
Changing to T= 50000 for T= 62370 logg=4.73
Changing to logg=5.00 for T= 62370 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 62370 logg=4.73
Changing to T= 50000 for T= 62821 logg=4.73
Changing to logg=5.00 for T= 62821 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 62821 logg=4.73
Changing to T= 50000 for T= 63314 logg=4.73
Changing to logg=5.00 for T= 63314 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63314 logg=4.73
Changing to T= 50000 for T= 63809 logg=4.73
Changing to logg=5.00 for T= 63809 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63809 logg=4.73
Changing to T= 50000 for T= 64301 logg=4.73
Changing to logg=5.00 for T= 64301 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64301 logg=4.73
Changing to T= 50000 for T= 64891 logg=4.73
Changing to logg=5.00 for T= 64891 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64891 logg=4.73
Changing to T= 50000 for T= 65728 logg=4.72
Changing to logg=5.00 for T= 65728 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 65728 logg=4.72
Changing to T= 50000 for T= 66610 logg=4.72
Changing to logg=5.00 for T= 66610 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 66610 logg=4.72
Changing to T= 50000 for T= 67458 logg=4.72
Changing to logg=5.00 for T= 67458 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 67458 logg=4.72
Changing to T= 50000 for T= 68175 logg=4.72
Changing to logg=5.00 for T= 68175 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 68175 logg=4.72
Changing to T= 50000 for T= 68691 logg=4.71
Changing to logg=5.00 for T= 68691 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 68691 logg=4.71
Changing to T= 50000 for T= 69223 logg=4.71
Changing to logg=5.00 for T= 69223 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 69223 logg=4.71
Changing to T= 50000 for T= 70468 logg=4.65
Changing to logg=5.00 for T= 70468 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 70468 logg=4.65
Changing to T= 50000 for T= 70997 logg=4.65
Changing to logg=5.00 for T= 70997 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 70997 logg=4.65
Changing to T= 50000 for T= 72115 logg=4.66
Changing to logg=5.00 for T= 72115 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72115 logg=4.66
Changing to T= 50000 for T= 72377 logg=4.66
Changing to logg=5.00 for T= 72377 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72377 logg=4.66
Changing to T= 50000 for T= 72967 logg=4.66
Changing to logg=5.00 for T= 72967 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 72967 logg=4.66
Changing to T= 50000 for T= 74037 logg=4.67
Changing to logg=5.00 for T= 74037 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74037 logg=4.67
Changing to T= 50000 for T= 74541 logg=4.67
Changing to logg=5.00 for T= 74541 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74541 logg=4.67
Changing to T= 50000 for T= 75133 logg=4.67
Changing to logg=5.00 for T= 75133 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 75133 logg=4.67
Changing to T= 50000 for T= 75716 logg=4.66
Changing to logg=5.00 for T= 75716 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 75716 logg=4.66
Isochrone generation took 5.434008 s.
Making photometry for isochrone: log(t) = 5.50  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:23.701457   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4122 K  m_2mass_J = 5.06
M =   3.131 Msun  T =  9333 K  m_2mass_J = -0.78

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  21.704 Msun  T = 49077 K  m_2mass_J = -1.92
Starting filter: 2mass,H   Elapsed time: 0.19 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4122 K  m_2mass_H = 4.56
M =   3.131 Msun  T =  9333 K  m_2mass_H = -0.79
M =  21.704 Msun  T = 49077 K  m_2mass_H = -1.81
      Time taken: 0.34 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4121 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4123 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4164 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4177 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4191 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4204 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4217 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4230 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4243 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4256 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4269 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4282 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4298 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4318 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4338 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4357 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4376 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4395 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4414 logg=3.47
Changing to met=-4.00 for met=-4.01 T=  4433 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4455 logg=3.48
Changing to met=-4.00 for met=-4.01 T=  4477 logg=3.49
Changing to met=-4.00 for met=-4.01 T=  4498 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4519 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4540 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4559 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4578 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4597 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4617 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4660 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4690 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4713 logg=3.55
Changing to met=-4.00 for met=-4.01 T=  4784 logg=3.56
Changing to met=-4.00 for met=-4.01 T=  4801 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4812 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4832 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4853 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4889 logg=3.58
Changing to met=-4.00 for met=-4.01 T=  4944 logg=3.59
Changing to met=-4.00 for met=-4.01 T=  4999 logg=3.60
Changing to met=-2.50 for met=-4.01 T=  5042 logg=3.61
Changing to met=-2.50 for met=-4.01 T=  5079 logg=3.61
Changing to met=-2.50 for met=-4.01 T=  5116 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5151 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5182 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5215 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5247 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5266 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5286 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5303 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5318 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5333 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5349 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5365 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5382 logg=3.63
Changing to met=-2.50 for met=-4.01 T=  5399 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5416 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5434 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5453 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5472 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5491 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5511 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5532 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5552 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5567 logg=3.62
Changing to met=-2.50 for met=-4.01 T=  5591 logg=3.61
Changing to met=-2.50 for met=-4.01 T=  5623 logg=3.61
Changing to met=-2.50 for met=-4.01 T=  5654 logg=3.60
Changing to met=-2.50 for met=-4.01 T=  5677 logg=3.60
Changing to met=-2.50 for met=-4.01 T=  5690 logg=3.59
Changing to met=-2.50 for met=-4.01 T=  5724 logg=3.58
Changing to met=-2.50 for met=-4.01 T=  5740 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5745 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5749 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5753 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  5772 logg=3.56
Changing to met=-2.50 for met=-4.01 T=  5809 logg=3.53
Changing to met=-2.50 for met=-4.01 T=  5856 logg=3.50
Changing to met=-2.50 for met=-4.01 T=  5907 logg=3.46
Changing to met=-2.50 for met=-4.01 T=  5969 logg=3.39
Changing to met=-2.50 for met=-4.01 T=  6045 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  6088 logg=3.27
Changing to met=-2.50 for met=-4.01 T=  6131 logg=3.24
Changing to met=-2.50 for met=-4.01 T=  6204 logg=3.21
Changing to met=-2.50 for met=-4.01 T=  6367 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  6530 logg=3.19
Changing to met=-2.50 for met=-4.01 T=  6889 logg=3.22
Changing to met=-2.50 for met=-4.01 T=  6947 logg=3.23
Changing to met=-2.50 for met=-4.01 T=  7365 logg=3.29
Changing to met=-2.50 for met=-4.01 T=  7532 logg=3.31
Changing to met=-2.50 for met=-4.01 T=  7668 logg=3.33
Changing to met=-2.50 for met=-4.01 T=  7808 logg=3.34
Changing to met=-2.50 for met=-4.01 T=  7989 logg=3.37
Changing to met=-2.50 for met=-4.01 T=  8211 logg=3.40
Changing to met=-2.50 for met=-4.01 T=  8439 logg=3.43
Changing to met=-2.50 for met=-4.01 T=  8674 logg=3.45
Changing to met=-2.50 for met=-4.01 T=  8914 logg=3.48
Changing to met=-2.50 for met=-4.01 T=  9162 logg=3.51
Changing to met=-2.50 for met=-4.01 T=  9416 logg=3.54
Changing to met=-2.50 for met=-4.01 T=  9677 logg=3.57
Changing to met=-2.50 for met=-4.01 T=  9945 logg=3.60
Changing to met=-2.50 for met=-4.01 T= 10221 logg=3.63
Changing to met=-2.50 for met=-4.01 T= 10504 logg=3.66
Changing to met=-2.50 for met=-4.01 T= 10795 logg=3.69
Changing to met=-2.50 for met=-4.01 T= 11094 logg=3.72
Changing to met=-2.50 for met=-4.01 T= 11402 logg=3.75
Changing to met=-2.50 for met=-4.01 T= 11718 logg=3.78
Changing to met=-2.50 for met=-4.01 T= 12043 logg=3.81
Changing to met=-2.50 for met=-4.01 T= 12376 logg=3.84
Changing to met=-2.50 for met=-4.01 T= 12718 logg=3.88
Changing to met=-2.50 for met=-4.01 T= 13068 logg=3.91
Changing to met=-2.50 for met=-4.01 T= 13429 logg=3.94
Changing to met=-2.50 for met=-4.01 T= 13799 logg=3.97
Changing to met=-2.50 for met=-4.01 T= 14171 logg=4.00
Changing to met=-2.50 for met=-4.01 T= 14549 logg=4.03
Changing to met=-2.50 for met=-4.01 T= 14939 logg=4.06
Changing to met=-2.50 for met=-4.01 T= 15339 logg=4.09
Changing to met=-2.50 for met=-4.01 T= 15752 logg=4.12
Changing to met=-2.50 for met=-4.01 T= 16177 logg=4.15
Changing to met=-2.50 for met=-4.01 T= 16616 logg=4.18
Changing to met=-2.50 for met=-4.01 T= 17067 logg=4.21
Changing to met=-2.50 for met=-4.01 T= 17527 logg=4.24
Changing to met=-2.50 for met=-4.01 T= 17996 logg=4.27
Changing to met=-2.50 for met=-4.01 T= 18478 logg=4.30
Changing to met=-2.50 for met=-4.01 T= 18965 logg=4.33
Changing to met=-2.50 for met=-4.01 T= 19447 logg=4.36
Changing to met=-2.50 for met=-4.01 T= 19941 logg=4.39
Changing to met=-2.50 for met=-4.01 T= 20449 logg=4.42
Changing to met=-2.50 for met=-4.01 T= 20970 logg=4.45
Changing to met=-2.50 for met=-4.01 T= 21505 logg=4.48
Changing to met=-2.50 for met=-4.01 T= 22053 logg=4.51
Changing to met=-2.50 for met=-4.01 T= 22610 logg=4.53
Changing to met=-2.50 for met=-4.01 T= 23181 logg=4.56
Changing to met=-2.50 for met=-4.01 T= 23769 logg=4.59
Changing to met=-2.50 for met=-4.01 T= 24380 logg=4.61
Changing to met=-2.50 for met=-4.01 T= 25007 logg=4.64
Changing to met=-2.50 for met=-4.01 T= 25632 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 26261 logg=4.70
Changing to met=-2.50 for met=-4.01 T= 26916 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 28861 logg=4.90
Changing to met=-2.50 for met=-4.01 T= 28209 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 29448 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 29532 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 29116 logg=4.88
Changing to met=-2.50 for met=-4.01 T= 30944 logg=4.88
Changing to met=-2.50 for met=-4.01 T= 30514 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 30088 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 29666 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 29248 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 29494 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 31959 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32238 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32512 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 32784 logg=4.87
Changing to met=-2.50 for met=-4.01 T= 33075 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33348 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33610 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 33879 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34153 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34421 logg=4.86
Changing to met=-2.50 for met=-4.01 T= 34701 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 34981 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35242 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35510 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 35782 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36044 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36309 logg=4.85
Changing to met=-2.50 for met=-4.01 T= 36584 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 36950 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37324 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 37712 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38086 logg=4.84
Changing to met=-2.50 for met=-4.01 T= 38416 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 38753 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39084 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39409 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 39709 logg=4.83
Changing to met=-2.50 for met=-4.01 T= 40017 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40324 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40630 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 40934 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41249 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41561 logg=4.82
Changing to met=-2.50 for met=-4.01 T= 41884 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42235 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42618 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 42991 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43377 logg=4.81
Changing to met=-2.50 for met=-4.01 T= 43748 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44122 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 44555 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45147 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 45633 logg=4.80
Changing to met=-2.50 for met=-4.01 T= 46032 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 46435 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 46844 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47255 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 47729 logg=4.79
Changing to met=-2.50 for met=-4.01 T= 48231 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 48735 logg=4.78
Changing to logg=5.00 for T= 49244 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49244 logg=4.78
Changing to logg=5.00 for T= 49758 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 49758 logg=4.78
Changing to T= 50000 for T= 50280 logg=4.78
Changing to logg=5.00 for T= 50280 logg=4.78
Changing to met=-2.50 for met=-4.01 T= 50280 logg=4.78
Changing to T= 50000 for T= 50808 logg=4.77
Changing to logg=5.00 for T= 50808 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 50808 logg=4.77
Changing to T= 50000 for T= 51341 logg=4.77
Changing to logg=5.00 for T= 51341 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51341 logg=4.77
Changing to T= 50000 for T= 51879 logg=4.77
Changing to logg=5.00 for T= 51879 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 51879 logg=4.77
Changing to T= 50000 for T= 52424 logg=4.77
Changing to logg=5.00 for T= 52424 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52424 logg=4.77
Changing to T= 50000 for T= 52975 logg=4.77
Changing to logg=5.00 for T= 52975 logg=4.77
Changing to met=-2.50 for met=-4.01 T= 52975 logg=4.77
Changing to T= 50000 for T= 53532 logg=4.76
Changing to logg=5.00 for T= 53532 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 53532 logg=4.76
Changing to T= 50000 for T= 54096 logg=4.76
Changing to logg=5.00 for T= 54096 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54096 logg=4.76
Changing to T= 50000 for T= 54666 logg=4.76
Changing to logg=5.00 for T= 54666 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 54666 logg=4.76
Changing to T= 50000 for T= 55242 logg=4.76
Changing to logg=5.00 for T= 55242 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55242 logg=4.76
Changing to T= 50000 for T= 55824 logg=4.76
Changing to logg=5.00 for T= 55824 logg=4.76
Changing to met=-2.50 for met=-4.01 T= 55824 logg=4.76
Changing to T= 50000 for T= 56380 logg=4.75
Changing to logg=5.00 for T= 56380 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 56380 logg=4.75
Changing to T= 50000 for T= 56833 logg=4.75
Changing to logg=5.00 for T= 56833 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 56833 logg=4.75
Changing to T= 50000 for T= 57343 logg=4.75
Changing to logg=5.00 for T= 57343 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 57343 logg=4.75
Changing to T= 50000 for T= 58319 logg=4.75
Changing to logg=5.00 for T= 58319 logg=4.75
Changing to met=-2.50 for met=-4.01 T= 58319 logg=4.75
Changing to T= 50000 for T= 58805 logg=4.74
Changing to logg=5.00 for T= 58805 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 58805 logg=4.74
Changing to T= 50000 for T= 59939 logg=4.74
Changing to logg=5.00 for T= 59939 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 59939 logg=4.74
Changing to T= 50000 for T= 60364 logg=4.74
Changing to logg=5.00 for T= 60364 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60364 logg=4.74
Changing to T= 50000 for T= 60794 logg=4.74
Changing to logg=5.00 for T= 60794 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 60794 logg=4.74
Changing to T= 50000 for T= 61229 logg=4.74
Changing to logg=5.00 for T= 61229 logg=4.74
Changing to met=-2.50 for met=-4.01 T= 61229 logg=4.74
Changing to T= 50000 for T= 61689 logg=4.73
Changing to logg=5.00 for T= 61689 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 61689 logg=4.73
Changing to T= 50000 for T= 62156 logg=4.73
Changing to logg=5.00 for T= 62156 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 62156 logg=4.73
Changing to T= 50000 for T= 62625 logg=4.73
Changing to logg=5.00 for T= 62625 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 62625 logg=4.73
Changing to T= 50000 for T= 63092 logg=4.73
Changing to logg=5.00 for T= 63092 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63092 logg=4.73
Changing to T= 50000 for T= 63568 logg=4.73
Changing to logg=5.00 for T= 63568 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 63568 logg=4.73
Changing to T= 50000 for T= 64094 logg=4.73
Changing to logg=5.00 for T= 64094 logg=4.73
Changing to met=-2.50 for met=-4.01 T= 64094 logg=4.73
Changing to T= 50000 for T= 64619 logg=4.72
Changing to logg=5.00 for T= 64619 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 64619 logg=4.72
Changing to T= 50000 for T= 65459 logg=4.72
Changing to logg=5.00 for T= 65459 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 65459 logg=4.72
Changing to T= 50000 for T= 66320 logg=4.72
Changing to logg=5.00 for T= 66320 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 66320 logg=4.72
Changing to T= 50000 for T= 67210 logg=4.72
Changing to logg=5.00 for T= 67210 logg=4.72
Changing to met=-2.50 for met=-4.01 T= 67210 logg=4.72
Changing to T= 50000 for T= 67993 logg=4.71
Changing to logg=5.00 for T= 67993 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 67993 logg=4.71
Changing to T= 50000 for T= 68501 logg=4.71
Changing to logg=5.00 for T= 68501 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 68501 logg=4.71
Changing to T= 50000 for T= 69025 logg=4.71
Changing to logg=5.00 for T= 69025 logg=4.71
Changing to met=-2.50 for met=-4.01 T= 69025 logg=4.71
Changing to T= 50000 for T= 70235 logg=4.65
Changing to logg=5.00 for T= 70235 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 70235 logg=4.65
Changing to T= 50000 for T= 70672 logg=4.65
Changing to logg=5.00 for T= 70672 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 70672 logg=4.65
Changing to T= 50000 for T= 72007 logg=4.65
Changing to logg=5.00 for T= 72007 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 72007 logg=4.65
Changing to T= 50000 for T= 72249 logg=4.65
Changing to logg=5.00 for T= 72249 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 72249 logg=4.65
Changing to T= 50000 for T= 72531 logg=4.65
Changing to logg=5.00 for T= 72531 logg=4.65
Changing to met=-2.50 for met=-4.01 T= 72531 logg=4.65
Changing to T= 50000 for T= 73761 logg=4.66
Changing to logg=5.00 for T= 73761 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 73761 logg=4.66
Changing to T= 50000 for T= 74348 logg=4.67
Changing to logg=5.00 for T= 74348 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74348 logg=4.67
Changing to T= 50000 for T= 74870 logg=4.67
Changing to logg=5.00 for T= 74870 logg=4.67
Changing to met=-2.50 for met=-4.01 T= 74870 logg=4.67
Changing to T= 50000 for T= 75399 logg=4.66
Changing to logg=5.00 for T= 75399 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 75399 logg=4.66
Changing to T= 50000 for T= 75996 logg=4.66
Changing to logg=5.00 for T= 75996 logg=4.66
Changing to met=-2.50 for met=-4.01 T= 75996 logg=4.66
Isochrone generation took 5.580343 s.
Making photometry for isochrone: log(t) = 5.55  AKs = 0.00  dist = 10
     Starting at:  2025-05-15 17:30:29.634375   Usually takes ~5 minutes
Starting filter: 2mass,J   Elapsed time: 0.00 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4121 K  m_2mass_J = 5.08
M =   3.028 Msun  T =  9416 K  m_2mass_J = -0.64
M =  20.395 Msun  T = 48231 K  m_2mass_J = -1.85
Starting filter: 2mass,H   Elapsed time: 0.19 seconds
Starting synthetic photometry
M =   0.100 Msun  T =  4121 K  m_2mass_H = 4.59
M =   3.028 Msun  T =  9416 K  m_2mass_H = -0.65

Requested metallicity 1.3999999999999997e-06 is out of bounds.

M =  20.395 Msun  T = 48231 K  m_2mass_H = -1.73
      Time taken: 0.35 seconds
-4.0061603087048185
Changing to met=-4.00 for met=-4.01 T=  4120 logg=3.55
Changing to met=-4.00 for met=-4.01 T=  4123 logg=3.55
Changing to met=-4.00 for met=-4.01 T=  4136 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4150 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4163 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4176 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4189 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4202 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4215 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4228 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4240 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4253 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4266 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4279 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4293 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4312 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4330 logg=3.50
Changing to met=-4.00 for met=-4.01 T=  4348 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4366 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4383 logg=3.51
Changing to met=-4.00 for met=-4.01 T=  4401 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4418 logg=3.52
Changing to met=-4.00 for met=-4.01 T=  4438 logg=3.53
Changing to met=-4.00 for met=-4.01 T=  4460 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4481 logg=3.54
Changing to met=-4.00 for met=-4.01 T=  4502 logg=3.55
Changing to met=-4.00 for met=-4.01 T=  4524 logg=3.55
Changing to met=-4.00 for met=-4.01 T=  4544 logg=3.56
Changing to met=-4.00 for met=-4.01 T=  4563 logg=3.56
Changing to met=-4.00 for met=-4.01 T=  4582 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4602 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4621 logg=3.57
Changing to met=-4.00 for met=-4.01 T=  4674 logg=3.58
Changing to met=-4.00 for met=-4.01 T=  4697 logg=3.59
Changing to met=-4.00 for met=-4.01 T=  4756 logg=3.60
Changing to met=-4.00 for met=-4.01 T=  4789 logg=3.61
Changing to met=-4.00 for met=-4.01 T=  4800 logg=3.61
Changing to met=-4.00 for met=-4.01 T=  4816 logg=3.61
Changing to met=-4.00 for met=-4.01 T=  4839 logg=3.61

In [51]:
import json
import pysynphot
from spisea import synthetic

In [64]:
with open('synthpop/modules/evolution/spisea_filters.json') as f:
    d = json.load(f)

In [67]:
def do_filts(sys,flts):
    efflamsi = {}
    for flt in flts:
            flt_name = sys+','+flt
            filt = synthetic.get_filter_info(flt_name)
            obs = pysynphot.Observation(pysynphot.Vega, filt).efflam()
            assert str(filt.waveunits) == 'angstrom'
            efflamsi[flt_name.replace(',','-')] = obs*1e-4
    return efflamsi

efflams = {}
for sys in d:
    flts = d[sys]
    if isinstance(flts,dict):
        for subsys in flts:
            efflams.update(do_filts(sys+','+subsys,flts[subsys]))
    else:
        efflams.update(do_filts(sys,flts))

(2MASS_J) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(2MASS_H) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(2MASS_Ks) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(ctio_osiris_H) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(ctio_osiris_K) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_u) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_g) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_r) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_i) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_z) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(decam_y) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(gaia_dr2_rev_Gbp) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(hawki_J) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(hawki_H) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(hawki_Ks) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f218w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f225w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f275w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f280n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f336w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f343n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f373n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f390m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f390w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f395n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f410m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f438w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f467m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f469n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f487n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f502n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f621m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f631n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f645n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f656n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f657n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f658n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f665n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f673n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f680n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f689m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f763m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f845m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,f953n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq232n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq243n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq378n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq387n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq422m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq436n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq437n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq492n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq508n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq575n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq619n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq634n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq672n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq674n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq727n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq750n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq889n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq906n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq924n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis1,fq937n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f218w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f225w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f275w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f280n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f336w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f343n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f373n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f390m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f390w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f395n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f410m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f438w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f467m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f469n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f487n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f502n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f621m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f631n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f645n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f656n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f657n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f658n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f665n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f673n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f680n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f689m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f763m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f845m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,f953n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq232n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq243n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq378n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq387n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq422m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq436n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq437n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq492n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq508n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq575n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq619n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq634n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq672n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq674n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq727n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq750n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq889n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq906n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq924n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,uvis2,fq937n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f098m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f105w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f110w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f125w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f126n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f127m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f128n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f130n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f132n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f139m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f140w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f153m) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f160w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f164n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(wfc3,ir,f167n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(acs,hrc,f344n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(acs,hrc,f435w) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(UnnamedArrayBandpass) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(acs,hrc,f502n) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

In [69]:
# Serializing json
json_object = json.dumps(efflams, indent=4)

# Writing to sample.json
with open("/Users/mhuston/Documents/synthpop/synthpop/config_files/AAA_effective_wavelengths_spisea.json", "w") as outfile:
    outfile.write(json_object)